import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

/**
 * TWO STALENESS QUESTIONS, AND ONLY ONE OF THEM WAS EVER ASKED.
 *
 * `--check` compares the catalog against `server/docs/swagger.json`. But that
 * document is generated by a MANUAL `swag init` upstream, so it goes stale on
 * its own — and when it does, every count inside this repo still agrees and the
 * missing operation is simply absent from a closed list nobody can see the end
 * of.
 *
 * Measured 2026-09-10: 490 routes annotated, 486 in the document. The four were
 * the AI chat assistant's whole configuration surface, mounted and live, with a
 * `chat-widget` element already shipping in the catalog — so an agent could put
 * a chat launcher on a page and had no call anywhere in its reach that could
 * turn the assistant on.
 *
 * These pin the three decisions that make the check useful rather than noisy.
 */
describe('codegen reports routes the swagger document does not carry', () => {
  let repo: string;
  const script = resolve(process.cwd(), 'scripts/gen-catalog.ts');

  const run = () =>
    spawnSync('npx', ['tsx', script, '--check'], {
      env: { ...process.env, WB_REPO: repo },
      encoding: 'utf8',
    });

  // COMMITTED, not merely written: `server/docs` is one of the four directories
  // the mid-edit guard watches, so a fixture that leaves it dirty never reaches
  // the code under test — it is turned away by a different check entirely.
  const swagger = (paths: Record<string, unknown>) => {
    writeFileSync(join(repo, 'server/docs/swagger.json'), JSON.stringify({ paths }));
    execFileSync('git', ['-C', repo, 'add', '-A'], { encoding: 'utf8' });
    execFileSync('git', ['-C', repo, 'commit', '-q', '--allow-empty', '-m', 'swagger'], {
      encoding: 'utf8',
    });
  };

  beforeAll(() => {
    repo = mkdtempSync(join(tmpdir(), 'wbroutes-'));
    mkdirSync(join(repo, 'server/internal/chatbot/rest'), { recursive: true });
    mkdirSync(join(repo, 'server/internal/courses/rest'), { recursive: true });
    mkdirSync(join(repo, 'server/docs'), { recursive: true });

    writeFileSync(
      join(repo, 'server/internal/chatbot/rest/rest.go'),
      [
        '// @Router   /api/sites/{siteId}/chat-settings [get]',
        '// @Router   /api/sites/{siteId}/chat-settings [put]',
        'func chatSettings() {}',
      ].join('\n'),
    );
    // The platform stacks one doc block over several @Router lines AND repeats a
    // route across blocks: courses/rest/rest.go declares the same two enrollment
    // routes twice. A raw `grep | wc -l` over-counts, which is exactly what the
    // shell recipe this check replaces told a reader to run.
    writeFileSync(
      join(repo, 'server/internal/courses/rest/rest.go'),
      [
        '// @Router   /api/sites/{siteId}/course-enrollments [get]',
        'func listA() {}',
        '// @Router   /api/sites/{siteId}/course-enrollments [get]',
        'func listB() {}',
      ].join('\n'),
    );

    const git = (...a: string[]) => execFileSync('git', ['-C', repo, ...a], { encoding: 'utf8' });
    git('init', '-q');
    git('config', 'user.email', 't@example.com');
    git('config', 'user.name', 'test');
    git('add', '-A');
    git('commit', '-qm', 'seed');
  });

  afterAll(() => rmSync(repo, { recursive: true, force: true }));

  it('names every annotated route the document is missing, and the upstream fix', () => {
    swagger({ '/api/sites/{siteId}/course-enrollments': { get: {} } });
    const r = run();
    expect(r.stderr).toMatch(/2 route\(s\) are ANNOTATED/);
    expect(r.stderr).toMatch(/GET \/api\/sites\/\{siteId\}\/chat-settings/);
    expect(r.stderr).toMatch(/PUT \/api\/sites\/\{siteId\}\/chat-settings/);
    // The fix is upstream. Saying "run codegen" would send the caller to the one
    // command that cannot recover a route the document does not carry.
    expect(r.stderr).toMatch(/swag init/);
    expect(r.stderr).toMatch(/Fix it UPSTREAM/);
  });

  it('counts a route annotated twice once', () => {
    swagger({ '/api/sites/{siteId}/course-enrollments': { get: {} } });
    // Three @Router lines across the fixture's two files, one of them a
    // duplicate: three distinct routes, not four.
    expect(run().stderr).toMatch(/\(3 annotated, 1 documented\)/);
  });

  it('matches on route SHAPE, so a renamed path parameter is not a false gap', () => {
    // swagger's own copy of a route may spell the parameter differently from the
    // annotation it came from. Comparing the raw strings would report every such
    // route as missing and bury the real ones.
    swagger({
      '/api/sites/{siteID}/chat-settings': { get: {}, put: {} },
      '/api/sites/{id}/course-enrollments': { get: {} },
    });
    const r = run();
    expect(r.stderr).not.toMatch(/are ANNOTATED/);
  });

  it('says nothing when the document carries everything', () => {
    swagger({
      '/api/sites/{siteId}/chat-settings': { get: {}, put: {} },
      '/api/sites/{siteId}/course-enrollments': { get: {} },
    });
    const r = run();
    expect(r.stderr).not.toMatch(/are ANNOTATED/);
    // And it never fails --check on its own: this drift is not fixable by
    // regenerating, so failing here would strand the caller.
    expect(r.stderr).not.toMatch(/catalog is STALE/);
  });
});
