// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/editor/src/features/courses/pageScaffold.ts (the platform's
// own course-app page scaffold) and <WB_REPO>/server/internal/builtinapps/
// builtinapps.go (the Keys roster).

/**
 * Every key `POST /api/sites/{siteId}/builtin-apps/{key}` accepts, in the
 * platform's own order — read off `builtinapps.Keys` rather than typed here,
 * and checked at codegen against that route's own `key` parameter description.
 */
export const BUILTIN_APP_KEYS = ["mail","multilingual","agent","chat","booking","loyalty","payments","courses"] as const;

/**
 * The pages an app needs that installing it does not create.
 *
 * `editor/src/features/builtinapps/pageScaffold.ts` runs this right after a
 * successful install (`scaffoldAppPages`) and offers it again as a repair.
 * `isPresent` is the rule for "does the site already have this one": a page
 * with a non-empty `slug` is present if the site has that SLUG (whatever its
 * type); a page with an empty `slug` is a TEMPLATE — reached by an entity
 * URL rather than an address of its own — and is present if the site has ANY
 * page of that TYPE, because the entity route resolves through the type's
 * default template and a second one would just sit there unreachable.
 * `sb_store action:"app"` follows the same rule.
 *
 * Only `courses` has one today; a key absent here installs with nothing
 * further to build.
 */
export const APP_SCAFFOLDS: Record<
  string,
  Array<{
    slug: string;
    type: string;
    name: { vi: string; en: string };
    document: { schema_version: number; root_node_id: string; nodes: Record<string, unknown> };
  }>
> = {
  "courses": [
    {
      "slug": "",
      "type": "course",
      "name": {
        "vi": "Trang khoá học",
        "en": "Course page"
      },
      "document": {
        "schema_version": 1,
        "root_node_id": "crs1_7",
        "nodes": {
          "crs1_1": {
            "id": "crs1_1",
            "data": {
              "type": "text-dataset",
              "parent": "crs1_6",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {
              "datasetSource": "course",
              "kind": "title",
              "textValue": "",
              "descriptionDisplayType": "Full",
              "descriptionLines": 3,
              "moreText": "Show more",
              "lessText": "Show less",
              "icon": true,
              "moreButtonColor": "#000000",
              "textGlobalStyle": "text-1"
            },
            "specials": {
              "htmlTag": "p",
              "moreButtonEnabled": false,
              "stylePreset": "text-dataset-default"
            },
            "responsive": {},
            "events": [],
            "bindings": [
              {
                "id": "bind-text",
                "source": "course.title",
                "field": "specials.boundText",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "title"
                }
              }
            ]
          },
          "crs1_2": {
            "id": "crs1_2",
            "data": {
              "type": "text-dataset",
              "parent": "crs1_6",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {
              "datasetSource": "course",
              "kind": "summary",
              "textValue": "",
              "descriptionDisplayType": "Full",
              "descriptionLines": 3,
              "moreText": "Show more",
              "lessText": "Show less",
              "icon": true,
              "moreButtonColor": "#000000",
              "textGlobalStyle": "text-1"
            },
            "specials": {
              "htmlTag": "p",
              "moreButtonEnabled": false,
              "stylePreset": "text-dataset-default"
            },
            "responsive": {},
            "events": [],
            "bindings": [
              {
                "id": "bind-text",
                "source": "course.summary",
                "field": "specials.boundText",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "summary"
                }
              }
            ]
          },
          "crs1_3": {
            "id": "crs1_3",
            "data": {
              "type": "text-dataset",
              "parent": "crs1_6",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {
              "datasetSource": "course",
              "kind": "price",
              "textValue": "",
              "descriptionDisplayType": "Full",
              "descriptionLines": 3,
              "moreText": "Show more",
              "lessText": "Show less",
              "icon": true,
              "moreButtonColor": "#000000",
              "textGlobalStyle": "text-1"
            },
            "specials": {
              "htmlTag": "p",
              "moreButtonEnabled": false,
              "stylePreset": "text-dataset-default"
            },
            "responsive": {},
            "events": [],
            "bindings": [
              {
                "id": "bind-text",
                "source": "course.price",
                "field": "specials.boundText",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "price"
                }
              }
            ]
          },
          "crs1_4": {
            "id": "crs1_4",
            "data": {
              "type": "button",
              "parent": "crs1_6",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "width": "fit-content",
              "height": "fit-content"
            },
            "config": {
              "iconSize": 20,
              "iconGap": 8,
              "iconPosition": "left"
            },
            "specials": {
              "text": "Button",
              "stylePreset": "button-default"
            },
            "responsive": {},
            "events": [
              {
                "id": "ev_click",
                "name": "click",
                "action": "open_cart",
                "payload": {}
              }
            ],
            "bindings": [
              {
                "id": "bind-product-action",
                "source": "product.id",
                "field": "specials.boundProductId",
                "target": {
                  "type": "product",
                  "id": "",
                  "action": "add_to_cart"
                }
              },
              {
                "id": "bind-course-product-id",
                "source": "course.enrolProductId",
                "field": "specials.boundEnrolProductId"
              }
            ]
          },
          "crs1_5": {
            "id": "crs1_5",
            "data": {
              "type": "text-dataset",
              "parent": "crs1_6",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {
              "datasetSource": "course",
              "kind": "description",
              "textValue": "",
              "descriptionDisplayType": "Full",
              "descriptionLines": 3,
              "moreText": "Show more",
              "lessText": "Show less",
              "icon": true,
              "moreButtonColor": "#000000",
              "textGlobalStyle": "text-1"
            },
            "specials": {
              "htmlTag": "p",
              "moreButtonEnabled": false,
              "stylePreset": "text-dataset-default"
            },
            "responsive": {},
            "events": [],
            "bindings": [
              {
                "id": "bind-text",
                "source": "course.description",
                "field": "specials.boundHtml",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "description"
                }
              }
            ]
          },
          "crs1_6": {
            "id": "crs1_6",
            "data": {
              "type": "flex-section",
              "parent": "crs1_7",
              "nodes": [
                "crs1_1",
                "crs1_2",
                "crs1_3",
                "crs1_4",
                "crs1_5"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "display": "flex",
              "flexDirection": "column",
              "width": "100%",
              "height": "fit-content"
            },
            "config": {
              "backgroundSceneSource": "",
              "backgroundSceneEffect": "gradient-mesh",
              "backgroundSceneGallery": "podium",
              "backgroundSceneSpeed": "normal",
              "backgroundSceneIntensity": "normal",
              "backgroundSceneColors": "theme",
              "backgroundSceneColor1": "#171717",
              "backgroundSceneColor2": "#ffffff",
              "backgroundSceneColor3": "#6b7280",
              "backgroundSceneUrl": "",
              "backgroundSceneModelUrl": "",
              "backgroundSceneVeil": 0,
              "backgroundSceneVeilColor": "#000000"
            },
            "specials": {
              "stylePreset": "container-section"
            },
            "responsive": {},
            "events": [],
            "bindings": []
          },
          "crs1_7": {
            "id": "crs1_7",
            "data": {
              "type": "root",
              "parent": null,
              "nodes": [
                "crs1_6"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {},
            "specials": {},
            "responsive": {},
            "events": [],
            "bindings": []
          }
        }
      }
    },
    {
      "slug": "courses",
      "type": "page",
      "name": {
        "vi": "Khoá học",
        "en": "Courses"
      },
      "document": {
        "schema_version": 1,
        "root_node_id": "crs2_7",
        "nodes": {
          "crs2_1": {
            "id": "crs2_1",
            "data": {
              "type": "list-dataset",
              "parent": "crs2_6",
              "nodes": [
                "crs2_2"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "width": "100%",
              "gap": "24px"
            },
            "config": {
              "datasetSource": "course",
              "articleSourceType": "category",
              "loadingMode": "none",
              "layout": "grid",
              "quantity": 4,
              "itemsPerRow": 4,
              "collectionType": "all_products",
              "collectionId": "all_products",
              "articleCategoryId": "all_articles",
              "collectionListType": "page_collections",
              "listNavIcon": "ArrowLeftSLine",
              "listNavPosition": "inside",
              "listNavIconSize": 16,
              "listNavIconColor": "#171717",
              "listNavButtonWidth": 32,
              "listNavButtonHeight": 32,
              "listNavButtonBg": "#ffffff",
              "paginationItemWidth": 8,
              "paginationItemHeight": 8,
              "paginationItemGap": 4,
              "paginationItemBg": "rgba(0,0,0,0.25)",
              "paginationItemActiveBg": "rgba(0,0,0,0.8)"
            },
            "specials": {
              "loadMoreLabel": "Load more",
              "collectionIds": []
            },
            "responsive": {
              "tablet": {
                "style": {
                  "gap": "20px"
                },
                "config": {
                  "itemsPerRow": 2
                }
              },
              "mobile": {
                "style": {
                  "gap": "16px"
                },
                "config": {
                  "itemsPerRow": 1
                }
              }
            },
            "events": [],
            "bindings": [
              {
                "id": "bind-target",
                "source": "",
                "field": "",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "course_list"
                }
              }
            ]
          },
          "crs2_2": {
            "id": "crs2_2",
            "data": {
              "type": "dataset-block",
              "parent": "crs2_1",
              "nodes": [
                "crs2_3",
                "crs2_4",
                "crs2_5"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "display": "flex",
              "flexDirection": "column",
              "gap": "24px",
              "padding": "24px",
              "backgroundColor": "#ffffff",
              "width": "100%",
              "height": "fit-content"
            },
            "config": {
              "contentWidth": "fill_container",
              "contentWidthCustom": 0,
              "backgroundSceneSource": "",
              "backgroundSceneEffect": "gradient-mesh",
              "backgroundSceneGallery": "podium",
              "backgroundSceneSpeed": "normal",
              "backgroundSceneIntensity": "normal",
              "backgroundSceneColors": "theme",
              "backgroundSceneColor1": "#171717",
              "backgroundSceneColor2": "#ffffff",
              "backgroundSceneColor3": "#6b7280",
              "backgroundSceneUrl": "",
              "backgroundSceneModelUrl": "",
              "backgroundSceneVeil": 0,
              "backgroundSceneVeilColor": "#000000",
              "datasetSource": "course"
            },
            "specials": {},
            "responsive": {
              "tablet": {
                "style": {
                  "padding": "20px",
                  "gap": "20px"
                }
              },
              "mobile": {
                "style": {
                  "padding": "16px",
                  "gap": "16px"
                }
              }
            },
            "events": [],
            "bindings": [
              {
                "id": "bind-href",
                "source": "course.url",
                "field": "specials.boundHref",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "course_general"
                }
              },
              {
                "id": "bind-href-label",
                "source": "course.title",
                "field": "specials.boundHrefLabel"
              }
            ]
          },
          "crs2_3": {
            "id": "crs2_3",
            "data": {
              "type": "collection-media",
              "parent": "crs2_2",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "width": "100%",
              "overflow": "hidden"
            },
            "config": {
              "imageRatio": "auto",
              "customImageRatioWidth": 16,
              "customImageRatioHeight": 9,
              "datasetSource": "course"
            },
            "specials": {
              "src": "",
              "alt": ""
            },
            "responsive": {},
            "events": [],
            "bindings": [
              {
                "id": "bind-image",
                "source": "course.image",
                "field": "specials.boundImage",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "media"
                }
              }
            ]
          },
          "crs2_4": {
            "id": "crs2_4",
            "data": {
              "type": "text-dataset",
              "parent": "crs2_2",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {
              "datasetSource": "course",
              "kind": "title",
              "textValue": "",
              "descriptionDisplayType": "Full",
              "descriptionLines": 3,
              "moreText": "Show more",
              "lessText": "Show less",
              "icon": true,
              "moreButtonColor": "#000000",
              "textGlobalStyle": "text-1"
            },
            "specials": {
              "htmlTag": "p",
              "moreButtonEnabled": false,
              "stylePreset": "text-dataset-default"
            },
            "responsive": {},
            "events": [],
            "bindings": [
              {
                "id": "bind-text",
                "source": "course.title",
                "field": "specials.boundText",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "title"
                }
              }
            ]
          },
          "crs2_5": {
            "id": "crs2_5",
            "data": {
              "type": "text-dataset",
              "parent": "crs2_2",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {
              "datasetSource": "course",
              "kind": "price",
              "textValue": "",
              "descriptionDisplayType": "Full",
              "descriptionLines": 3,
              "moreText": "Show more",
              "lessText": "Show less",
              "icon": true,
              "moreButtonColor": "#000000",
              "textGlobalStyle": "text-1"
            },
            "specials": {
              "htmlTag": "p",
              "moreButtonEnabled": false,
              "stylePreset": "text-dataset-default"
            },
            "responsive": {},
            "events": [],
            "bindings": [
              {
                "id": "bind-text",
                "source": "course.price",
                "field": "specials.boundText",
                "target": {
                  "type": "course",
                  "id": "",
                  "kind": "price"
                }
              }
            ]
          },
          "crs2_6": {
            "id": "crs2_6",
            "data": {
              "type": "flex-section",
              "parent": "crs2_7",
              "nodes": [
                "crs2_1"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "display": "flex",
              "flexDirection": "column",
              "width": "100%",
              "height": "fit-content"
            },
            "config": {
              "backgroundSceneSource": "",
              "backgroundSceneEffect": "gradient-mesh",
              "backgroundSceneGallery": "podium",
              "backgroundSceneSpeed": "normal",
              "backgroundSceneIntensity": "normal",
              "backgroundSceneColors": "theme",
              "backgroundSceneColor1": "#171717",
              "backgroundSceneColor2": "#ffffff",
              "backgroundSceneColor3": "#6b7280",
              "backgroundSceneUrl": "",
              "backgroundSceneModelUrl": "",
              "backgroundSceneVeil": 0,
              "backgroundSceneVeilColor": "#000000"
            },
            "specials": {
              "stylePreset": "container-section"
            },
            "responsive": {},
            "events": [],
            "bindings": []
          },
          "crs2_7": {
            "id": "crs2_7",
            "data": {
              "type": "root",
              "parent": null,
              "nodes": [
                "crs2_6"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {},
            "specials": {},
            "responsive": {},
            "events": [],
            "bindings": []
          }
        }
      }
    },
    {
      "slug": "learn",
      "type": "page",
      "name": {
        "vi": "Học bài",
        "en": "Learning"
      },
      "document": {
        "schema_version": 1,
        "root_node_id": "crs3_3",
        "nodes": {
          "crs3_1": {
            "id": "crs3_1",
            "data": {
              "type": "course-player",
              "parent": "crs3_2",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "width": "100%"
            },
            "config": {},
            "specials": {
              "courseId": "",
              "lockedText": "Bạn chưa có quyền học bài này.",
              "lockedLabel": "Xem khoá học",
              "lockedHref": "",
              "emptyText": "Khoá học này chưa có bài nào.",
              "completeLabel": "Đánh dấu hoàn thành",
              "completedLabel": "Đã hoàn thành",
              "certificateText": "Bạn đã hoàn thành khoá học và đạt chứng chỉ.",
              "showOutline": true,
              "autoComplete": true
            },
            "responsive": {},
            "events": [],
            "bindings": []
          },
          "crs3_2": {
            "id": "crs3_2",
            "data": {
              "type": "flex-section",
              "parent": "crs3_3",
              "nodes": [
                "crs3_1"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "display": "flex",
              "flexDirection": "column",
              "width": "100%",
              "height": "fit-content"
            },
            "config": {
              "backgroundSceneSource": "",
              "backgroundSceneEffect": "gradient-mesh",
              "backgroundSceneGallery": "podium",
              "backgroundSceneSpeed": "normal",
              "backgroundSceneIntensity": "normal",
              "backgroundSceneColors": "theme",
              "backgroundSceneColor1": "#171717",
              "backgroundSceneColor2": "#ffffff",
              "backgroundSceneColor3": "#6b7280",
              "backgroundSceneUrl": "",
              "backgroundSceneModelUrl": "",
              "backgroundSceneVeil": 0,
              "backgroundSceneVeilColor": "#000000"
            },
            "specials": {
              "stylePreset": "container-section"
            },
            "responsive": {},
            "events": [],
            "bindings": []
          },
          "crs3_3": {
            "id": "crs3_3",
            "data": {
              "type": "root",
              "parent": null,
              "nodes": [
                "crs3_2"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {},
            "specials": {},
            "responsive": {},
            "events": [],
            "bindings": []
          }
        }
      }
    },
    {
      "slug": "my-courses",
      "type": "page",
      "name": {
        "vi": "Khoá học của tôi",
        "en": "My courses"
      },
      "document": {
        "schema_version": 1,
        "root_node_id": "crs4_3",
        "nodes": {
          "crs4_1": {
            "id": "crs4_1",
            "data": {
              "type": "my-courses",
              "parent": "crs4_2",
              "nodes": [],
              "isCanvas": false,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "width": "100%"
            },
            "config": {},
            "specials": {
              "emptyText": "Bạn chưa có khoá học nào.",
              "signedOutText": "Đăng nhập để xem khoá học của bạn.",
              "continueText": "Tiếp tục học",
              "learnHref": "/learn"
            },
            "responsive": {},
            "events": [],
            "bindings": []
          },
          "crs4_2": {
            "id": "crs4_2",
            "data": {
              "type": "flex-section",
              "parent": "crs4_3",
              "nodes": [
                "crs4_1"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {
              "display": "flex",
              "flexDirection": "column",
              "width": "100%",
              "height": "fit-content"
            },
            "config": {
              "backgroundSceneSource": "",
              "backgroundSceneEffect": "gradient-mesh",
              "backgroundSceneGallery": "podium",
              "backgroundSceneSpeed": "normal",
              "backgroundSceneIntensity": "normal",
              "backgroundSceneColors": "theme",
              "backgroundSceneColor1": "#171717",
              "backgroundSceneColor2": "#ffffff",
              "backgroundSceneColor3": "#6b7280",
              "backgroundSceneUrl": "",
              "backgroundSceneModelUrl": "",
              "backgroundSceneVeil": 0,
              "backgroundSceneVeilColor": "#000000"
            },
            "specials": {
              "stylePreset": "container-section"
            },
            "responsive": {},
            "events": [],
            "bindings": []
          },
          "crs4_3": {
            "id": "crs4_3",
            "data": {
              "type": "root",
              "parent": null,
              "nodes": [
                "crs4_2"
              ],
              "isCanvas": true,
              "hidden": false,
              "custom": {}
            },
            "style": {},
            "config": {},
            "specials": {},
            "responsive": {},
            "events": [],
            "bindings": []
          }
        }
      }
    }
  ]
};
