// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/editor/src/element/{formTemplates,checkoutPageSeed}.ts and
//         <WB_REPO>/editor/src/i18n/locales/*/editorPanel.json

/** The placeholder `sb_store` replaces with the form it just created. */
export const FORM_ID_SENTINEL = "__SB_CHECKOUT_FORM_ID__";
export const HEADLINE_SENTINEL = '__SB_HEADLINE__';

export const CHECKOUT_FORM = {
  "type": "order",
  "settings": {
    "orderSource": "cart"
  }
} as const;

export const CHECKOUT_FORM_DOCUMENT = {
  "root_node_id": "ckf_1",
  "nodes": {
    "ckf_1": {
      "id": "ckf_1",
      "data": {
        "type": "form",
        "parent": null,
        "nodes": [
          "ckf_2",
          "ckf_3",
          "ckf_4",
          "ckf_5",
          "ckf_6",
          "ckf_7",
          "ckf_8",
          "ckf_9",
          "ckf_10",
          "ckf_11",
          "ckf_12",
          "ckf_13"
        ],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "column",
        "width": "100%",
        "height": "fit-content",
        "gap": "16px"
      },
      "config": {},
      "specials": {
        "formId": "",
        "segmentId": "",
        "formRules": ""
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_2": {
      "id": "ckf_2",
      "data": {
        "type": "form-title",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%",
        "height": "fit-content",
        "textAlign": "left",
        "lineHeight": "130%",
        "fontSize": "20px",
        "fontWeight": "600",
        "color": "#171717"
      },
      "config": {},
      "specials": {
        "htmlTag": "h3",
        "text": "Thanh toán"
      },
      "responsive": {
        "mobile": {
          "style": {
            "fontSize": "18px"
          }
        }
      },
      "events": [],
      "bindings": []
    },
    "ckf_3": {
      "id": "ckf_3",
      "data": {
        "type": "form-text",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {
        "iconPosition": "left"
      },
      "specials": {
        "showIcon": false,
        "iconName": "",
        "name": "full_name",
        "label": "Họ và tên",
        "placeholder": "",
        "description": "",
        "required": true,
        "showLabel": true,
        "mapTo": "customer.fullName",
        "prefillValue": "",
        "multiline": false,
        "inputType": "text",
        "limitChars": false,
        "minChars": 0,
        "maxChars": 500,
        "patternPreset": "",
        "pattern": "",
        "patternCountries": []
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_4": {
      "id": "ckf_4",
      "data": {
        "type": "form-text",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {
        "iconPosition": "left"
      },
      "specials": {
        "showIcon": false,
        "iconName": "",
        "name": "phone",
        "label": "Số điện thoại",
        "placeholder": "",
        "description": "",
        "required": true,
        "showLabel": true,
        "mapTo": "customer.phone",
        "prefillValue": "",
        "multiline": false,
        "inputType": "tel",
        "limitChars": false,
        "minChars": 0,
        "maxChars": 500,
        "patternPreset": "",
        "pattern": "",
        "patternCountries": []
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_5": {
      "id": "ckf_5",
      "data": {
        "type": "form-text",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {
        "iconPosition": "left"
      },
      "specials": {
        "showIcon": false,
        "iconName": "",
        "name": "email",
        "label": "Email",
        "placeholder": "",
        "description": "",
        "required": false,
        "showLabel": true,
        "mapTo": "customer.email",
        "prefillValue": "",
        "multiline": false,
        "inputType": "email",
        "limitChars": false,
        "minChars": 0,
        "maxChars": 500,
        "patternPreset": "",
        "pattern": "",
        "patternCountries": []
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_6": {
      "id": "ckf_6",
      "data": {
        "type": "form-address",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {},
      "specials": {
        "name": "tinh_thanh",
        "label": "Tỉnh / Thành phố",
        "description": "",
        "required": true,
        "showLabel": true,
        "mapTo": "customer.state",
        "part": "province",
        "addressLink": true,
        "addressGroup": "",
        "provinceField": "",
        "allowedCodes": [],
        "presetCode": "",
        "copyFrom": "",
        "sameDefault": true,
        "placeholder": "Chọn tỉnh / thành phố",
        "provinceLabel": "Tỉnh / Thành phố",
        "wardLabel": "Phường / Xã",
        "detailLabel": "Số nhà, tên đường",
        "provincePlaceholder": "Chọn tỉnh / thành phố",
        "wardPlaceholder": "Chọn phường / xã",
        "detailPlaceholder": "Ví dụ: 12 Nguyễn Huệ",
        "showDetail": true,
        "country": "VN"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_7": {
      "id": "ckf_7",
      "data": {
        "type": "form-address",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {},
      "specials": {
        "name": "phuong_xa",
        "label": "Phường / Xã",
        "description": "",
        "required": true,
        "showLabel": true,
        "mapTo": "customer.ward",
        "part": "ward",
        "addressLink": true,
        "addressGroup": "",
        "provinceField": "",
        "allowedCodes": [],
        "presetCode": "",
        "copyFrom": "",
        "sameDefault": true,
        "placeholder": "Chọn phường / xã",
        "provinceLabel": "Tỉnh / Thành phố",
        "wardLabel": "Phường / Xã",
        "detailLabel": "Số nhà, tên đường",
        "provincePlaceholder": "Chọn tỉnh / thành phố",
        "wardPlaceholder": "Chọn phường / xã",
        "detailPlaceholder": "Ví dụ: 12 Nguyễn Huệ",
        "showDetail": true,
        "country": "VN"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_8": {
      "id": "ckf_8",
      "data": {
        "type": "form-address",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {},
      "specials": {
        "name": "dia_chi",
        "label": "Số nhà, tên đường",
        "description": "",
        "required": true,
        "showLabel": true,
        "mapTo": "customer.address",
        "part": "street",
        "addressLink": true,
        "addressGroup": "",
        "provinceField": "",
        "allowedCodes": [],
        "presetCode": "",
        "copyFrom": "",
        "sameDefault": true,
        "placeholder": "Ví dụ: 12 Nguyễn Huệ",
        "provinceLabel": "Tỉnh / Thành phố",
        "wardLabel": "Phường / Xã",
        "detailLabel": "Số nhà, tên đường",
        "provincePlaceholder": "Chọn tỉnh / thành phố",
        "wardPlaceholder": "Chọn phường / xã",
        "detailPlaceholder": "Ví dụ: 12 Nguyễn Huệ",
        "showDetail": true,
        "country": "VN"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_9": {
      "id": "ckf_9",
      "data": {
        "type": "form-select",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {
        "optionSource": "manual"
      },
      "specials": {
        "name": "shipping_method",
        "label": "Phương thức vận chuyển",
        "description": "",
        "required": false,
        "showLabel": true,
        "mapTo": "order.shippingMethod",
        "options": [],
        "defaultValue": "",
        "placeholder": "Chọn phương thức vận chuyển"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_10": {
      "id": "ckf_10",
      "data": {
        "type": "form-text",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {
        "iconPosition": "left"
      },
      "specials": {
        "showIcon": false,
        "iconName": "",
        "name": "discount_code",
        "label": "Mã giảm giá",
        "placeholder": "Nhập mã nếu có",
        "description": "",
        "required": false,
        "showLabel": true,
        "mapTo": "order.discountCode",
        "prefillValue": "",
        "multiline": false,
        "inputType": "text",
        "limitChars": false,
        "minChars": 0,
        "maxChars": 500,
        "patternPreset": "",
        "pattern": "",
        "patternCountries": []
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_11": {
      "id": "ckf_11",
      "data": {
        "type": "form-payment",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {},
      "specials": {
        "name": "payment_method",
        "label": "Phương thức thanh toán",
        "description": "",
        "required": true,
        "showLabel": true,
        "mapTo": "order.paymentMethod",
        "methods": [],
        "defaultValue": "",
        "showLogos": true,
        "logoShape": "auto",
        "showMarker": true
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_12": {
      "id": "ckf_12",
      "data": {
        "type": "form-text",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%"
      },
      "config": {
        "iconPosition": "left"
      },
      "specials": {
        "showIcon": false,
        "iconName": "",
        "name": "order_note",
        "label": "Ghi chú",
        "placeholder": "",
        "description": "",
        "required": false,
        "showLabel": true,
        "mapTo": "order.note",
        "prefillValue": "",
        "multiline": true,
        "inputType": "text",
        "limitChars": false,
        "minChars": 0,
        "maxChars": 500,
        "patternPreset": "",
        "pattern": "",
        "patternCountries": []
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckf_13": {
      "id": "ckf_13",
      "data": {
        "type": "form-submit",
        "parent": "ckf_1",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%",
        "padding": "10px 16px",
        "backgroundColor": "#171717",
        "color": "#ffffff",
        "borderRadius": "6px"
      },
      "config": {},
      "specials": {
        "text": "Đặt hàng",
        "submittingText": "Đang gửi…"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    }
  }
};

export const CHECKOUT_PAGE_DOCUMENT = {
  "schema_version": 2,
  "root_node_id": "ckp_1",
  "nodes": {
    "ckp_1": {
      "id": "ckp_1",
      "data": {
        "type": "root",
        "parent": null,
        "nodes": [
          "ckp_2"
        ],
        "isCanvas": true,
        "hidden": false,
        "custom": {}
      },
      "style": {},
      "config": {},
      "specials": {},
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_2": {
      "id": "ckp_2",
      "data": {
        "type": "flex-section",
        "parent": "ckp_1",
        "nodes": [
          "ckp_3",
          "ckp_4",
          "ckp_5",
          "ckp_6",
          "ckp_7",
          "ckp_8",
          "ckp_9"
        ],
        "isCanvas": true,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "column",
        "width": "100%",
        "height": "fit-content",
        "gap": "24px",
        "paddingTop": "48px",
        "paddingBottom": "48px"
      },
      "config": {},
      "specials": {
        "stylePreset": "container-section"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_3": {
      "id": "ckp_3",
      "data": {
        "type": "heading",
        "parent": "ckp_2",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "width": "100%",
        "height": "fit-content"
      },
      "config": {
        "textGlobalStyle": "heading-1"
      },
      "specials": {
        "htmlTag": "h1",
        "text": "__SB_HEADLINE__",
        "stylePreset": "heading-default"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_4": {
      "id": "ckp_4",
      "data": {
        "type": "cart-total",
        "parent": "ckp_2",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "row",
        "justifyContent": "space-between",
        "alignItems": "center",
        "width": "100%",
        "gap": "12px",
        "fontSize": "16px",
        "fontWeight": "400",
        "color": "#171717"
      },
      "config": {},
      "specials": {
        "label": "Tạm tính",
        "placeholder": "0 ₫",
        "part": "subtotal"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_5": {
      "id": "ckp_5",
      "data": {
        "type": "cart-total",
        "parent": "ckp_2",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "row",
        "justifyContent": "space-between",
        "alignItems": "center",
        "width": "100%",
        "gap": "12px",
        "fontSize": "16px",
        "fontWeight": "400",
        "color": "#171717"
      },
      "config": {},
      "specials": {
        "label": "Giảm giá",
        "placeholder": "0 ₫",
        "part": "discount"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_6": {
      "id": "ckp_6",
      "data": {
        "type": "cart-total",
        "parent": "ckp_2",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "row",
        "justifyContent": "space-between",
        "alignItems": "center",
        "width": "100%",
        "gap": "12px",
        "fontSize": "16px",
        "fontWeight": "400",
        "color": "#171717"
      },
      "config": {},
      "specials": {
        "label": "Phí vận chuyển",
        "placeholder": "0 ₫",
        "part": "shipping"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_7": {
      "id": "ckp_7",
      "data": {
        "type": "cart-total",
        "parent": "ckp_2",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "row",
        "justifyContent": "space-between",
        "alignItems": "center",
        "width": "100%",
        "gap": "12px",
        "fontSize": "16px",
        "fontWeight": "600",
        "color": "#171717"
      },
      "config": {},
      "specials": {
        "label": "Tổng cộng",
        "placeholder": "0 ₫",
        "part": "total"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_8": {
      "id": "ckp_8",
      "data": {
        "type": "cart-total",
        "parent": "ckp_2",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "row",
        "justifyContent": "space-between",
        "alignItems": "center",
        "width": "100%",
        "gap": "12px",
        "fontSize": "16px",
        "fontWeight": "600",
        "color": "#171717"
      },
      "config": {},
      "specials": {
        "label": "Còn phải trả",
        "placeholder": "0 ₫",
        "part": "due"
      },
      "responsive": {},
      "events": [],
      "bindings": []
    },
    "ckp_9": {
      "id": "ckp_9",
      "data": {
        "type": "form",
        "parent": "ckp_2",
        "nodes": [],
        "isCanvas": false,
        "hidden": false,
        "custom": {}
      },
      "style": {
        "display": "flex",
        "flexDirection": "column",
        "width": "100%",
        "height": "fit-content",
        "gap": "12px"
      },
      "config": {},
      "specials": {
        "formId": "__SB_CHECKOUT_FORM_ID__",
        "segmentId": "",
        "formRules": ""
      },
      "responsive": {},
      "events": [],
      "bindings": []
    }
  }
};

/** The editor's own words, so a store built by an agent reads like one built by hand. */
export const CHECKOUT_TEXT = {
  "vi": {
    "formName": "Thanh toán (giỏ hàng)",
    "pageName": "Thanh toán",
    "headline": "Thanh toán",
    "codLabel": "Thanh toán khi nhận hàng",
    "paymentDesc": {
      "cod": "Trả tiền mặt cho người giao khi nhận hàng.",
      "sepay": "Chuyển khoản ngân hàng — nhận số tài khoản và nội dung chuyển khoản ngay sau khi đặt.",
      "vnpay": "Thẻ ATM, thẻ quốc tế hoặc ví VNPay — chuyển sang trang VNPay để thanh toán.",
      "momo": "Quét mã hoặc mở ứng dụng MoMo để thanh toán.",
      "payos": "Chuyển khoản qua mã QR — xác nhận tự động ngay khi tiền về.",
      "zalopay": "Mở ứng dụng ZaloPay để thanh toán.",
      "stripe": "Thẻ Visa, Mastercard hoặc thẻ quốc tế khác.",
      "paypal": "Thanh toán bằng tài khoản PayPal hoặc thẻ quốc tế.",
      "gateway": "Chuyển sang trang của cổng thanh toán để hoàn tất."
    }
  },
  "en": {
    "formName": "Checkout (cart)",
    "pageName": "Checkout",
    "headline": "Checkout",
    "codLabel": "Cash on delivery",
    "paymentDesc": {
      "cod": "Pay the courier in cash when the order arrives.",
      "sepay": "Bank transfer — the account number and reference appear right after you order.",
      "vnpay": "ATM card, international card or VNPay wallet — you are taken to VNPay to pay.",
      "momo": "Scan a code or open the MoMo app to pay.",
      "payos": "Bank transfer by QR code — confirmed automatically when the money lands.",
      "zalopay": "Open the ZaloPay app to pay.",
      "stripe": "Visa, Mastercard or another international card.",
      "paypal": "Pay with a PayPal account or an international card.",
      "gateway": "You are taken to the payment gateway to finish."
    }
  }
} as const;
