// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: every identifier in <WB_REPO>/{schema/src,editor/src,server,runtime}, excluding each
// element's own meta.ts (a seed is not a reader). See scripts/deadkey-scan.ts.
import type { DeadKey } from './element-types.js';

export const DEAD_KEY_SOURCE = {
  "files": 3974,
  "identifiers": 76582,
  "seededKeys": 384,
  "dead": 0
} as const;

/**
 * Keys an element SEEDS and no renderer anywhere reads.
 *
 * Keyed by the key NAME, not by `namespace.key`: the index is a flat set of
 * identifiers, so it cannot tell one namespace from the other and a key read
 * anywhere is read in both.
 *
 * A write to one of these stores, saves, publishes and renders exactly as
 * before. `sb_set` says so at the moment of the write; nothing refuses it,
 * because the platform accepts the value and a refusal here would invent a rule
 * it does not have.
 */
export const DEAD_KEYS: Record<string, DeadKey> = {};
