// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/schema/src/elements/fieldSkin.ts (the vocabulary) and each
// server/render/nodes/form*/css.go (which node emits which group).

export const FIELD_SKIN_SOURCE = {
  "nodes": 11,
  "keys": 55
} as const;

/**
 * The field-skin config keys each form node's renderer actually reads.
 *
 * A knob written on a node that is not in its list is stored, saved, published
 * and rendered NOWHERE — the documented case being payCard* on the FORM, which
 * emits only the input vocabulary. Composed from the TS groups and asserted
 * against the Go's own key literals at codegen.
 */
export const FIELD_SKIN_BY_NODE: Record<string, string[]> = {
  "form": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "fieldBg",
    "fieldBorderColor",
    "fieldBorderWidth",
    "fieldRadius",
    "fieldPadY",
    "fieldPadX"
  ],
  "form-calendar": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "fieldBg",
    "fieldBorderColor",
    "fieldBorderWidth",
    "fieldRadius",
    "fieldPadY",
    "fieldPadX"
  ],
  "form-checkbox": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "choiceRowGap",
    "choiceColGap",
    "choiceGap",
    "choiceSize",
    "choiceBorderWidth",
    "choiceBorderColor",
    "choiceBg",
    "choiceAccent",
    "choiceRadius",
    "choiceMarkWidth"
  ],
  "form-date": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "fieldBg",
    "fieldBorderColor",
    "fieldBorderWidth",
    "fieldRadius",
    "fieldPadY",
    "fieldPadX"
  ],
  "form-file": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "fileGap",
    "filePlaceholderWeight"
  ],
  "form-number": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "fieldBg",
    "fieldBorderColor",
    "fieldBorderWidth",
    "fieldRadius",
    "fieldPadY",
    "fieldPadX"
  ],
  "form-payment": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "payCardBg",
    "payCardBorderColor",
    "payCardBorderWidth",
    "payCardRadius",
    "payCardPadY",
    "payCardPadX",
    "payCardGap",
    "payCardRowGap",
    "payCardAccent",
    "payCardSelectedBg",
    "payCardHoverColor",
    "payCardHoverBg",
    "payCardText",
    "payCardNameWeight",
    "payCardDescOpacity",
    "payCardBodyGap",
    "payMarkerSize",
    "payMarkerDot"
  ],
  "form-radio": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "choiceRowGap",
    "choiceColGap",
    "choiceGap",
    "choiceSize",
    "choiceBorderWidth",
    "choiceBorderColor",
    "choiceBg",
    "choiceAccent",
    "choiceDot"
  ],
  "form-select": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "fieldBg",
    "fieldBorderColor",
    "fieldBorderWidth",
    "fieldRadius",
    "fieldPadY",
    "fieldPadX"
  ],
  "form-text": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "fieldBg",
    "fieldBorderColor",
    "fieldBorderWidth",
    "fieldRadius",
    "fieldPadY",
    "fieldPadX"
  ],
  "form-timeslot": [
    "fieldStackGap",
    "fieldReqColor",
    "fieldHintOpacity",
    "slotBg",
    "slotBorderColor",
    "slotBorderWidth",
    "slotRadius",
    "slotPadY",
    "slotPadX",
    "slotGap",
    "slotMinWidth",
    "slotMinHeight",
    "slotAccent",
    "slotHoverColor",
    "slotSelectedWeight",
    "slotMarkerSize",
    "slotMarkerDot",
    "slotMarkerGap"
  ]
};
