// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/schema/src/elements/formRules.ts (RULE_ACTIONS, RuleJoin) and
// schema/src/elements/fieldCondition.ts (CONDITION_OPS), asserted against
// server/internal/forms/{rules,condition}.go.

/**
 * The vocabulary of `specials.formRules` on a form root. A rule using a word
 * outside these lists is DROPPED by every reader (editor, page, server) with no
 * error, so the field it governs simply never changes.
 */
export const FORM_RULE_VOCAB = {
  "joins": [
    "and",
    "or"
  ],
  "ops": [
    "is",
    "isNot",
    "filled",
    "empty",
    "contains",
    "notContains"
  ],
  "actions": [
    "hidden",
    "shown",
    "optional",
    "required"
  ]
} as const;
