// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/editor/src/features/overlays/seed.ts (the editor's own overlay seeds).

/**
 * The document envelope the overlays API stores — {root_node_id, nodes}, the
 * same two fields a page document carries minus schema_version:
 * `CreateOverlayInput.document` is typed `unknown` on the platform and held
 * opaque, so there is nothing else for this envelope to declare.
 */
export interface OverlayDocument {
  root_node_id: string;
  nodes: Record<string, unknown>;
}

/**
 * WHAT A FRESH POP-UP AND A FRESH QUICK VIEW ARRIVE HOLDING, read by calling
 * the editor's OWN seed functions rather than copied from their output — the
 * day either card gains a piece it arrives at both doors.
 *
 * A placeholder, not a value: node ids here are stable across codegen runs
 * (so `--check` reports real drift only), and `sb_store` mints FRESH ids on
 * every real attach, exactly as the editor does on every real drop.
 */
export const OVERLAY_SEEDS: Record<'popup' | 'quickview', OverlayDocument> = {
  "popup": {
    "root_node_id": "pop_1",
    "nodes": {
      "pop_1": {
        "id": "pop_1",
        "data": {
          "type": "popup",
          "parent": null,
          "nodes": [
            "pop_2",
            "pop_3",
            "pop_4"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "width": "460px",
          "maxWidth": "calc(100% - 32px)",
          "gap": "12px",
          "padding": "24px",
          "backgroundColor": "#ffffff",
          "borderTopLeftRadius": "10px",
          "borderTopRightRadius": "10px",
          "borderBottomLeftRadius": "10px",
          "borderBottomRightRadius": "10px",
          "overflowX": "auto",
          "overflowY": "auto"
        },
        "config": {
          "placement": "center",
          "overlayColor": "#000000",
          "clickToClose": true,
          "triggerType": "",
          "triggerDelay": 2,
          "triggerFreq": "once",
          "closeIconSize": 16,
          "closeIconColor": "#000000",
          "closeW": 28,
          "closeH": 28,
          "closeBg": "#F5F5F5",
          "closeRadius": 20,
          "closePos": "inside",
          "effect": "fade"
        },
        "specials": {
          "closeLabel": "Close",
          "closeIcon": "CloseLine"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "pop_2": {
        "id": "pop_2",
        "data": {
          "type": "heading",
          "parent": "pop_1",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "height": "fit-content",
          "fontSize": "20px"
        },
        "config": {
          "textGlobalStyle": "heading-1"
        },
        "specials": {
          "htmlTag": "h2",
          "text": "Pop-up",
          "stylePreset": "heading-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "pop_3": {
        "id": "pop_3",
        "data": {
          "type": "text",
          "parent": "pop_1",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "text": "Tell your visitors what this is about.",
          "stylePreset": "text-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "pop_4": {
        "id": "pop_4",
        "data": {
          "type": "button",
          "parent": "pop_1",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "iconSize": 20,
          "iconGap": 8,
          "iconPosition": "left"
        },
        "specials": {
          "text": "Got it",
          "stylePreset": "button-default"
        },
        "responsive": {},
        "events": [
          {
            "id": "ev_click",
            "name": "click",
            "action": "close_popup",
            "payload": {}
          }
        ],
        "bindings": []
      }
    }
  },
  "quickview": {
    "root_node_id": "qv_1",
    "nodes": {
      "qv_1": {
        "id": "qv_1",
        "data": {
          "type": "quickview",
          "parent": null,
          "nodes": [
            "qv_2",
            "qv_20"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "gap": "16px",
          "width": "720px",
          "maxWidth": "calc(100% - 32px)",
          "maxHeight": "calc(100vh - 64px)",
          "padding": "24px",
          "backgroundColor": "#ffffff",
          "borderTopLeftRadius": "10px",
          "borderTopRightRadius": "10px",
          "borderBottomLeftRadius": "10px",
          "borderBottomRightRadius": "10px",
          "overflowX": "hidden",
          "overflowY": "auto"
        },
        "config": {
          "showOverlay": true,
          "overlayColor": "#000000",
          "clickToClose": true
        },
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "qv_2": {
        "id": "qv_2",
        "data": {
          "type": "icon",
          "parent": "qv_1",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "fit-content",
          "height": "fit-content",
          "alignSelf": "flex-end"
        },
        "config": {
          "iconSize": 24
        },
        "specials": {
          "name": "CloseLine",
          "stylePreset": "icon-default"
        },
        "responsive": {},
        "events": [
          {
            "id": "ev_close_quick_view",
            "name": "click",
            "action": "close_quick_view",
            "payload": {}
          }
        ],
        "bindings": []
      },
      "qv_3": {
        "id": "qv_3",
        "data": {
          "type": "media-dataset",
          "parent": "qv_20",
          "nodes": [
            "qv_4",
            "qv_5"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "layout": "single",
          "activeIndex": 0
        },
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          }
        ]
      },
      "qv_4": {
        "id": "qv_4",
        "data": {
          "type": "product-image-feature",
          "parent": "qv_3",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "showNav": true,
          "listNavPosition": "inside",
          "listNavButtonWidth": 40,
          "listNavButtonHeight": 40,
          "listNavIconColor": "#000000",
          "listNavButtonBg": "#ffffff",
          "paginationBg": "rgba(0,0,0,0.20)",
          "paginationItemBg": "rgba(255,255,255,0.40)",
          "paginationItemActiveBg": "#FFFFFF",
          "paginationItemWidth": 8,
          "paginationItemHeight": 8,
          "paginationItemGap": 4,
          "featureClickAction": "open_gallery",
          "hoverSwapImage": false,
          "mainImageSource": "first_variant"
        },
        "specials": {
          "alt": ""
        },
        "responsive": {
          "tablet": {
            "config": {
              "listNavButtonWidth": 36,
              "listNavButtonHeight": 36
            }
          },
          "mobile": {
            "config": {
              "listNavButtonWidth": 32,
              "listNavButtonHeight": 32
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          },
          {
            "id": "bind-product-url",
            "source": "product.url",
            "field": "specials.boundProductURL"
          }
        ]
      },
      "qv_5": {
        "id": "qv_5",
        "data": {
          "type": "product-image-list",
          "parent": "qv_3",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "itemSize": 60,
          "gap": 12,
          "listItemImageRatio": "1 / 1",
          "listNavButtonBg": "rgba(255,255,255,0.60)",
          "listNavIconColor": "#000000"
        },
        "specials": {},
        "responsive": {
          "tablet": {
            "config": {
              "itemSize": 52
            }
          },
          "mobile": {
            "config": {
              "itemSize": 44,
              "gap": 8
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "qv_6": {
        "id": "qv_6",
        "data": {
          "type": "flex-block",
          "parent": "qv_20",
          "nodes": [
            "qv_7",
            "qv_8",
            "qv_11",
            "qv_14",
            "qv_15",
            "qv_18",
            "qv_19"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "alignItems": "flex-start",
          "justifyContent": "flex-start",
          "width": "100%",
          "height": "fit-content",
          "gap": "16px"
        },
        "config": {
          "contentWidth": "fill_container",
          "backgroundSceneSource": "",
          "backgroundSceneEffect": "gradient-mesh",
          "backgroundSceneGallery": "podium",
          "backgroundSceneSpeed": "normal",
          "backgroundSceneIntensity": "normal",
          "backgroundSceneColors": "theme",
          "backgroundSceneColor1": "#171717",
          "backgroundSceneColor2": "#ffffff",
          "backgroundSceneColor3": "#6b7280",
          "backgroundSceneUrl": "",
          "backgroundSceneModelUrl": "",
          "backgroundSceneVeil": 0,
          "backgroundSceneVeilColor": "#000000"
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "style": {
              "flexDirection": "column"
            }
          }
        },
        "events": [],
        "bindings": []
      },
      "qv_7": {
        "id": "qv_7",
        "data": {
          "type": "text-dataset",
          "parent": "qv_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "28px"
        },
        "config": {
          "datasetSource": "product",
          "kind": "title",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "heading-3"
        },
        "specials": {
          "htmlTag": "h3",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "product.title",
            "field": "specials.boundText",
            "target": {
              "type": "product",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "qv_8": {
        "id": "qv_8",
        "data": {
          "type": "pricing-dataset",
          "parent": "qv_6",
          "nodes": [
            "qv_9",
            "qv_10"
          ],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px",
          "padding": "0px",
          "width": "100%",
          "height": "auto"
        },
        "config": {
          "kind": "prices",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "prices"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "qv_9": {
        "id": "qv_9",
        "data": {
          "type": "pricing-dataset",
          "parent": "qv_8",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px",
          "color": "#000000",
          "fontSize": "16px",
          "lineHeight": "140%",
          "textAlign": "left",
          "fontFamily": "Inter"
        },
        "config": {
          "kind": "price",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "price"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "qv_10": {
        "id": "qv_10",
        "data": {
          "type": "pricing-dataset",
          "parent": "qv_8",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px",
          "color": "#7f7f7f",
          "fontSize": "16px",
          "lineHeight": "140%",
          "textAlign": "left",
          "fontFamily": "Inter"
        },
        "config": {
          "kind": "compare_price",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "compare_price"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "qv_11": {
        "id": "qv_11",
        "data": {
          "type": "product-variants",
          "parent": "qv_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "gap": "16px"
        },
        "config": {
          "attributes": [
            {
              "name": "Color",
              "values": [
                "Red",
                "Green",
                "Blue"
              ]
            },
            {
              "name": "Size",
              "values": [
                "S",
                "M",
                "L"
              ]
            }
          ],
          "variantLabel": {
            "active": true,
            "direction": "vertical",
            "gap": 8
          },
          "optionGap": "",
          "variantLabelId": "qv_12",
          "variantOptionId": "qv_13"
        },
        "specials": {
          "displayType": "image_label",
          "defaultVariant": {
            "enabled": false,
            "values": {}
          }
        },
        "responsive": {
          "mobile": {
            "style": {
              "gap": "12px"
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-attributes",
            "source": "product.attributes",
            "field": "specials.boundAttributes",
            "target": {
              "type": "product",
              "id": "",
              "kind": "variants"
            }
          },
          {
            "id": "bind-variations",
            "source": "product.variations",
            "field": "specials.boundVariations"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "qv_12": {
        "id": "qv_12",
        "data": {
          "type": "product-variant-label",
          "parent": "qv_11",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontFamily": "Inter",
          "color": "#000000",
          "lineHeight": "1.3",
          "fontWeight": "700",
          "textAlign": "left"
        },
        "config": {
          "textGlobalStyle": "heading-6"
        },
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "qv_13": {
        "id": "qv_13",
        "data": {
          "type": "product-variant-option",
          "parent": "qv_11",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontFamily": "Inter",
          "fontSize": "16px",
          "color": "#171717",
          "lineHeight": "1.3",
          "borderColor": "#d0d0d0",
          "borderWidth": "1px",
          "borderStyle": "solid",
          "borderRadius": "0",
          "backgroundColor": "#ffffff",
          "padding": "16px 12px",
          "gap": "12px",
          "--variant-image-width": "48px",
          "--variant-image-height": "48px"
        },
        "config": {
          "textGlobalStyle": "text-1",
          "variantImage": {
            "active": true,
            "size": 24,
            "gap": 12
          }
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "style": {
              "padding": "12px 10px",
              "gap": "8px",
              "--variant-image-width": "40px"
            }
          }
        },
        "states": {
          "hover": {
            "style": {
              "backgroundColor": "#f5f5f5"
            }
          },
          "active": {
            "style": {
              "borderColor": "#171717",
              "backgroundColor": "#ffffff"
            }
          }
        },
        "events": [],
        "bindings": []
      },
      "qv_14": {
        "id": "qv_14",
        "data": {
          "type": "text-dataset",
          "parent": "qv_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {
          "datasetSource": "product",
          "kind": "description",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "moreButtonEnabled": true,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "product.description",
            "field": "specials.boundHtml",
            "target": {
              "type": "product",
              "id": "",
              "kind": "description"
            }
          }
        ]
      },
      "qv_15": {
        "id": "qv_15",
        "data": {
          "type": "quantity-dataset",
          "parent": "qv_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "inline-flex",
          "width": "fit-content",
          "alignItems": "center",
          "borderWidth": "1px",
          "borderStyle": "solid",
          "borderColor": "#d0d0d0",
          "borderRadius": "8px",
          "overflow": "hidden"
        },
        "config": {
          "defaultNum": 1,
          "quantityButtonId": "qv_16",
          "quantityInputId": "qv_17"
        },
        "specials": {
          "button": true
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId",
            "target": {
              "type": "product",
              "id": "",
              "kind": "quantity"
            }
          }
        ]
      },
      "qv_16": {
        "id": "qv_16",
        "data": {
          "type": "quantity-button",
          "parent": "qv_15",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "backgroundColor": "#f8f8f8"
        },
        "config": {
          "iconSize": 20
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "config": {
              "iconSize": 18
            }
          }
        },
        "states": {
          "hover": {
            "style": {
              "backgroundColor": "#f1f1f1"
            }
          }
        },
        "events": [],
        "bindings": []
      },
      "qv_17": {
        "id": "qv_17",
        "data": {
          "type": "quantity-input",
          "parent": "qv_15",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {
          "stylePreset": "quantity-input-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "qv_18": {
        "id": "qv_18",
        "data": {
          "type": "button",
          "parent": "qv_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "iconSize": 20,
          "iconGap": 8,
          "iconPosition": "left",
          "textGlobalStyle": "heading-6",
          "stateHover": {
            "backgroundColor": "#333333"
          }
        },
        "specials": {
          "text": "Add To Cart",
          "stylePreset": "button-default",
          "icon": "ShoppingCart2Fill"
        },
        "responsive": {},
        "events": [
          {
            "id": "ev_click",
            "name": "click",
            "action": "open_cart",
            "payload": {}
          }
        ],
        "bindings": [
          {
            "id": "bind-product-action",
            "source": "product.id",
            "field": "specials.boundProductId",
            "target": {
              "type": "product",
              "id": "",
              "action": "add_to_cart"
            }
          },
          {
            "id": "bind-course-product-id",
            "source": "course.enrolProductId",
            "field": "specials.boundEnrolProductId"
          }
        ]
      },
      "qv_19": {
        "id": "qv_19",
        "data": {
          "type": "button",
          "parent": "qv_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "iconSize": 20,
          "iconGap": 8,
          "iconPosition": "left",
          "textGlobalStyle": "heading-6",
          "stateHover": {
            "backgroundColor": "#333333"
          }
        },
        "specials": {
          "text": "Buy It Now",
          "stylePreset": "button-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-product-action",
            "source": "product.id",
            "field": "specials.boundProductId",
            "target": {
              "type": "product",
              "id": "",
              "action": "dynamic_checkout"
            }
          },
          {
            "id": "bind-course-product-id",
            "source": "course.enrolProductId",
            "field": "specials.boundEnrolProductId"
          }
        ]
      },
      "qv_20": {
        "id": "qv_20",
        "data": {
          "type": "flex-block",
          "parent": "qv_1",
          "nodes": [
            "qv_3",
            "qv_6"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "row",
          "alignItems": "flex-start",
          "justifyContent": "flex-start",
          "width": "100%",
          "gap": "16px",
          "padding": "0px",
          "backgroundColor": "#ffffff",
          "height": "fit-content"
        },
        "config": {
          "contentWidth": "fill_container",
          "backgroundSceneSource": "",
          "backgroundSceneEffect": "gradient-mesh",
          "backgroundSceneGallery": "podium",
          "backgroundSceneSpeed": "normal",
          "backgroundSceneIntensity": "normal",
          "backgroundSceneColors": "theme",
          "backgroundSceneColor1": "#171717",
          "backgroundSceneColor2": "#ffffff",
          "backgroundSceneColor3": "#6b7280",
          "backgroundSceneUrl": "",
          "backgroundSceneModelUrl": "",
          "backgroundSceneVeil": 0,
          "backgroundSceneVeilColor": "#000000"
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "style": {
              "flexDirection": "column"
            }
          }
        },
        "events": [],
        "bindings": []
      }
    }
  }
} as const;
