// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// The platform commit every other generated file here describes.

export const PLATFORM_SOURCE: {
  /** web_builder's HEAD when this ran, or null where there is no git to ask. */
  commit: string | null;
  /** That commit's own date (ISO), which is what makes staleness readable. */
  committedAt: string | null;
  /** True when `--dirty` read a working tree, so half-finished work can be described here. */
  dirty: boolean;
} = {
  "commit": "84f1f10bcbef0748d0b18e19283ccb0458599c1b",
  "committedAt": "2026-09-26T21:25:06+07:00",
  "dirty": false
};
