// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// The platform commit every other generated file here describes.

export const PLATFORM_SOURCE: {
  /** web_builder's HEAD when this ran, or null where there is no git to ask. */
  commit: string | null;
  /** That commit's own date (ISO), which is what makes staleness readable. */
  committedAt: string | null;
  /** True when `--dirty` read a working tree, so half-finished work can be described here. */
  dirty: boolean;
} = {
  "commit": "d6a68b77a7a00a6a9ca66da5161d57e845aae628",
  "committedAt": "2026-09-17T00:01:02+07:00",
  "dirty": false
};
