// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// The platform commit every other generated file here describes.

export const PLATFORM_SOURCE: {
  /** web_builder's HEAD when this ran, or null where there is no git to ask. */
  commit: string | null;
  /** That commit's own date (ISO), which is what makes staleness readable. */
  committedAt: string | null;
  /** True when `--dirty` read a working tree, so half-finished work can be described here. */
  dirty: boolean;
} = {
  "commit": "a3a7352834d9d774f5a8162663fe8b27a0422d22",
  "committedAt": "2026-09-26T11:21:05+07:00",
  "dirty": false
};
