// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/editor/src/element/storePageSeeds.ts (the palette's own cards).

export const STORE_SEED_SOURCE = {
  "types": [
    "product",
    "category",
    "search",
    "blog",
    "post",
    "complete"
  ],
  "nodes": {
    "product": 24,
    "category": 14,
    "search": 14,
    "blog": 13,
    "post": 6,
    "complete": 5
  }
} as const;

/** The token the completion page's thank-you headline is substituted into. */
export const COMPLETION_HEADLINE_SENTINEL = "__SB_COMPLETION_HEADLINE__";

/**
 * The thank-you sentence, per locale, as the editor ships it.
 *
 * Read from the platform rather than defaulted, so a Vietnamese store does not
 * get an English seeded page — the defect `default_seed_copy` reports.
 */
export const COMPLETION_HEADLINE: Record<string, string> = {
  "vi": "Cảm ơn bạn đã đặt hàng",
  "en": "Thank you for your order"
};

/**
 * The document a new page of each type opens with in the EDITOR.
 *
 * Not a copy of the palette — built by calling the palette's own cards, so an
 * agent that creates a product page and a merchant who drags the Product card
 * end up looking at the same thing. A type absent here starts blank, which is
 * the right default for `page` itself.
 */
export const STORE_PAGE_SEEDS: Record<string, { schema_version: number; root_node_id: string; nodes: Record<string, unknown> }> = {
  "product": {
    "schema_version": 2,
    "root_node_id": "sppro_1",
    "nodes": {
      "sppro_1": {
        "id": "sppro_1",
        "data": {
          "type": "root",
          "parent": null,
          "nodes": [
            "sppro_24"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppro_2": {
        "id": "sppro_2",
        "data": {
          "type": "dataset-block",
          "parent": "sppro_24",
          "nodes": [
            "sppro_3",
            "sppro_6"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "row",
          "gap": "16px",
          "padding": "0px",
          "backgroundColor": "#ffffff",
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "contentWidth": "fill_container",
          "contentWidthCustom": 0,
          "emptyStateId": "sppro_20"
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "style": {
              "flexDirection": "column"
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-href",
            "source": "product.url",
            "field": "specials.boundHref",
            "target": {
              "type": "product",
              "id": "",
              "kind": "product_general"
            }
          },
          {
            "id": "bind-href-label",
            "source": "product.title",
            "field": "specials.boundHrefLabel"
          }
        ]
      },
      "sppro_3": {
        "id": "sppro_3",
        "data": {
          "type": "media-dataset",
          "parent": "sppro_2",
          "nodes": [
            "sppro_4",
            "sppro_5"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "layout": "single",
          "activeIndex": 0
        },
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          }
        ]
      },
      "sppro_4": {
        "id": "sppro_4",
        "data": {
          "type": "product-image-feature",
          "parent": "sppro_3",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "showNav": true,
          "listNavPosition": "inside",
          "listNavButtonWidth": 40,
          "listNavButtonHeight": 40,
          "listNavIconColor": "#000000",
          "listNavButtonBg": "#ffffff",
          "paginationBg": "rgba(0,0,0,0.20)",
          "paginationItemBg": "rgba(255,255,255,0.40)",
          "paginationItemActiveBg": "#FFFFFF",
          "paginationItemWidth": 8,
          "paginationItemHeight": 8,
          "paginationItemGap": 4,
          "featureClickAction": "open_gallery",
          "hoverSwapImage": false,
          "mainImageSource": "first_variant"
        },
        "specials": {
          "alt": ""
        },
        "responsive": {
          "tablet": {
            "config": {
              "listNavButtonWidth": 36,
              "listNavButtonHeight": 36
            }
          },
          "mobile": {
            "config": {
              "listNavButtonWidth": 32,
              "listNavButtonHeight": 32
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          },
          {
            "id": "bind-product-url",
            "source": "product.url",
            "field": "specials.boundProductURL"
          }
        ]
      },
      "sppro_5": {
        "id": "sppro_5",
        "data": {
          "type": "product-image-list",
          "parent": "sppro_3",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "itemSize": 60,
          "gap": 12,
          "listItemImageRatio": "1 / 1",
          "listNavButtonBg": "rgba(255,255,255,0.60)",
          "listNavIconColor": "#000000"
        },
        "specials": {},
        "responsive": {
          "tablet": {
            "config": {
              "itemSize": 52
            }
          },
          "mobile": {
            "config": {
              "itemSize": 44,
              "gap": 8
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "sppro_6": {
        "id": "sppro_6",
        "data": {
          "type": "flex-block",
          "parent": "sppro_2",
          "nodes": [
            "sppro_7",
            "sppro_8",
            "sppro_11",
            "sppro_14",
            "sppro_15",
            "sppro_18",
            "sppro_19"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "alignItems": "flex-start",
          "justifyContent": "flex-start",
          "width": "100%",
          "height": "fit-content",
          "gap": "16px"
        },
        "config": {
          "contentWidth": "fill_container"
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "style": {
              "flexDirection": "column"
            }
          }
        },
        "events": [],
        "bindings": []
      },
      "sppro_7": {
        "id": "sppro_7",
        "data": {
          "type": "text-dataset",
          "parent": "sppro_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "28px"
        },
        "config": {
          "datasetSource": "product",
          "kind": "title",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "heading-3"
        },
        "specials": {
          "htmlTag": "h3",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "product.title",
            "field": "specials.boundText",
            "target": {
              "type": "product",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "sppro_8": {
        "id": "sppro_8",
        "data": {
          "type": "pricing-dataset",
          "parent": "sppro_6",
          "nodes": [
            "sppro_9",
            "sppro_10"
          ],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px",
          "padding": "0px",
          "width": "100%",
          "height": "auto"
        },
        "config": {
          "kind": "prices",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "prices"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "sppro_9": {
        "id": "sppro_9",
        "data": {
          "type": "pricing-dataset",
          "parent": "sppro_8",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px",
          "color": "#000000",
          "fontSize": "16px",
          "lineHeight": "140%",
          "textAlign": "left",
          "fontFamily": "Inter"
        },
        "config": {
          "kind": "price",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "price"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "sppro_10": {
        "id": "sppro_10",
        "data": {
          "type": "pricing-dataset",
          "parent": "sppro_8",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px",
          "color": "#7f7f7f",
          "fontSize": "16px",
          "lineHeight": "140%",
          "textAlign": "left",
          "fontFamily": "Inter"
        },
        "config": {
          "kind": "compare_price",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "compare_price"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "sppro_11": {
        "id": "sppro_11",
        "data": {
          "type": "product-variants",
          "parent": "sppro_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "gap": "16px"
        },
        "config": {
          "attributes": [
            {
              "name": "Color",
              "values": [
                "Red",
                "Green",
                "Blue"
              ]
            },
            {
              "name": "Size",
              "values": [
                "S",
                "M",
                "L"
              ]
            }
          ],
          "variantLabel": {
            "active": true,
            "direction": "vertical",
            "gap": 8
          },
          "optionGap": "",
          "variantLabelId": "sppro_12",
          "variantOptionId": "sppro_13"
        },
        "specials": {
          "displayType": "image_label",
          "defaultVariant": {
            "enabled": false,
            "values": {}
          }
        },
        "responsive": {
          "mobile": {
            "style": {
              "gap": "12px"
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-attributes",
            "source": "product.attributes",
            "field": "specials.boundAttributes",
            "target": {
              "type": "product",
              "id": "",
              "kind": "variants"
            }
          },
          {
            "id": "bind-variations",
            "source": "product.variations",
            "field": "specials.boundVariations"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "sppro_12": {
        "id": "sppro_12",
        "data": {
          "type": "product-variant-label",
          "parent": "sppro_11",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontFamily": "Inter",
          "color": "#000000",
          "lineHeight": "1.3",
          "fontWeight": "700",
          "textAlign": "left"
        },
        "config": {
          "textGlobalStyle": "heading-6"
        },
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppro_13": {
        "id": "sppro_13",
        "data": {
          "type": "product-variant-option",
          "parent": "sppro_11",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontFamily": "Inter",
          "fontSize": "16px",
          "color": "#171717",
          "lineHeight": "1.3",
          "borderColor": "#d0d0d0",
          "borderWidth": "1px",
          "borderStyle": "solid",
          "borderRadius": "0",
          "backgroundColor": "#ffffff",
          "padding": "16px 12px",
          "gap": "12px",
          "--variant-image-width": "48px",
          "--variant-image-height": "48px"
        },
        "config": {
          "textGlobalStyle": "text-1",
          "variantImage": {
            "active": true,
            "size": 24,
            "gap": 12
          }
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "style": {
              "padding": "12px 10px",
              "gap": "8px",
              "--variant-image-width": "40px"
            }
          }
        },
        "states": {
          "hover": {
            "style": {
              "backgroundColor": "#f5f5f5"
            }
          },
          "active": {
            "style": {
              "borderColor": "#171717",
              "backgroundColor": "#ffffff"
            }
          }
        },
        "events": [],
        "bindings": []
      },
      "sppro_14": {
        "id": "sppro_14",
        "data": {
          "type": "text-dataset",
          "parent": "sppro_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {
          "datasetSource": "product",
          "kind": "description",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "moreButtonEnabled": true,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "product.description",
            "field": "specials.boundHtml",
            "target": {
              "type": "product",
              "id": "",
              "kind": "description"
            }
          }
        ]
      },
      "sppro_15": {
        "id": "sppro_15",
        "data": {
          "type": "quantity-dataset",
          "parent": "sppro_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "inline-flex",
          "width": "fit-content",
          "alignItems": "center",
          "borderWidth": "1px",
          "borderStyle": "solid",
          "borderColor": "#d0d0d0",
          "borderRadius": "8px",
          "overflow": "hidden"
        },
        "config": {
          "defaultNum": 1,
          "quantityButtonId": "sppro_16",
          "quantityInputId": "sppro_17"
        },
        "specials": {
          "button": true
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId",
            "target": {
              "type": "product",
              "id": "",
              "kind": "quantity"
            }
          }
        ]
      },
      "sppro_16": {
        "id": "sppro_16",
        "data": {
          "type": "quantity-button",
          "parent": "sppro_15",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "backgroundColor": "#f8f8f8"
        },
        "config": {
          "iconSize": 20
        },
        "specials": {},
        "responsive": {
          "mobile": {
            "config": {
              "iconSize": 18
            }
          }
        },
        "states": {
          "hover": {
            "style": {
              "backgroundColor": "#f1f1f1"
            }
          }
        },
        "events": [],
        "bindings": []
      },
      "sppro_17": {
        "id": "sppro_17",
        "data": {
          "type": "quantity-input",
          "parent": "sppro_15",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {
          "stylePreset": "quantity-input-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppro_18": {
        "id": "sppro_18",
        "data": {
          "type": "button",
          "parent": "sppro_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "iconSize": 20,
          "iconGap": 8,
          "iconPosition": "left",
          "textGlobalStyle": "heading-6",
          "stateHover": {
            "backgroundColor": "#333333"
          }
        },
        "specials": {
          "text": "Add To Cart",
          "stylePreset": "button-default",
          "icon": "ShoppingCart2Fill"
        },
        "responsive": {},
        "events": [
          {
            "id": "ev_click",
            "name": "click",
            "action": "open_cart",
            "payload": {}
          }
        ],
        "bindings": [
          {
            "id": "bind-product-action",
            "source": "product.id",
            "field": "specials.boundProductId",
            "target": {
              "type": "product",
              "id": "",
              "action": "add_to_cart"
            }
          },
          {
            "id": "bind-course-product-id",
            "source": "course.enrolProductId",
            "field": "specials.boundEnrolProductId"
          }
        ]
      },
      "sppro_19": {
        "id": "sppro_19",
        "data": {
          "type": "button",
          "parent": "sppro_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "iconSize": 20,
          "iconGap": 8,
          "iconPosition": "left",
          "textGlobalStyle": "heading-6",
          "stateHover": {
            "backgroundColor": "#333333"
          }
        },
        "specials": {
          "text": "Buy It Now",
          "stylePreset": "button-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-product-action",
            "source": "product.id",
            "field": "specials.boundProductId",
            "target": {
              "type": "product",
              "id": "",
              "action": "dynamic_checkout"
            }
          },
          {
            "id": "bind-course-product-id",
            "source": "course.enrolProductId",
            "field": "specials.boundEnrolProductId"
          }
        ]
      },
      "sppro_20": {
        "id": "sppro_20",
        "data": {
          "type": "list-empty",
          "parent": "sppro_2",
          "nodes": [
            "sppro_21",
            "sppro_22",
            "sppro_23"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "alignItems": "center",
          "justifyContent": "center",
          "gap": "12px",
          "width": "100%",
          "padding": "48px 24px 48px 24px"
        },
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppro_21": {
        "id": "sppro_21",
        "data": {
          "type": "icon",
          "parent": "sppro_20",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "fit-content",
          "height": "fit-content",
          "color": "#d4d4d4"
        },
        "config": {
          "iconSize": 32
        },
        "specials": {
          "name": "ShoppingBag3Line",
          "stylePreset": "icon-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppro_22": {
        "id": "sppro_22",
        "data": {
          "type": "heading",
          "parent": "sppro_20",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "20px",
          "fontWeight": "600",
          "color": "#171717",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "heading-1"
        },
        "specials": {
          "htmlTag": "h3",
          "text": "This item is unavailable",
          "stylePreset": "heading-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppro_23": {
        "id": "sppro_23",
        "data": {
          "type": "text",
          "parent": "sppro_20",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "14px",
          "color": "#737373",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "text": "It may have been removed. Have a look at the rest of the shop.",
          "stylePreset": "text-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppro_24": {
        "id": "sppro_24",
        "data": {
          "type": "flex-section",
          "parent": "sppro_1",
          "nodes": [
            "sppro_2"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "width": "100%",
          "height": "fit-content",
          "gap": "24px",
          "paddingTop": "48px",
          "paddingBottom": "48px"
        },
        "config": {},
        "specials": {
          "stylePreset": "container-section"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      }
    }
  },
  "category": {
    "schema_version": 2,
    "root_node_id": "spcat_1",
    "nodes": {
      "spcat_1": {
        "id": "spcat_1",
        "data": {
          "type": "root",
          "parent": null,
          "nodes": [
            "spcat_14"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcat_2": {
        "id": "spcat_2",
        "data": {
          "type": "text-dataset",
          "parent": "spcat_14",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "28px"
        },
        "config": {
          "datasetSource": "category",
          "kind": "title",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "heading-3"
        },
        "specials": {
          "htmlTag": "h3",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "category.title",
            "field": "specials.boundText",
            "target": {
              "type": "category",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "spcat_3": {
        "id": "spcat_3",
        "data": {
          "type": "list-dataset",
          "parent": "spcat_14",
          "nodes": [
            "spcat_4"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "gap": "24px"
        },
        "config": {
          "datasetSource": "product",
          "articleSourceType": "category",
          "loadingMode": "none",
          "layout": "grid",
          "quantity": 4,
          "itemsPerRow": 4,
          "collectionType": "all_products",
          "collectionId": "all_products",
          "articleCategoryId": "all_articles",
          "collectionListType": "all_collections",
          "listNavIcon": "ArrowLeftSLine",
          "listNavPosition": "inside",
          "listNavIconSize": 16,
          "listNavIconColor": "#171717",
          "listNavButtonWidth": 32,
          "listNavButtonHeight": 32,
          "listNavButtonBg": "#ffffff",
          "paginationItemWidth": 8,
          "paginationItemHeight": 8,
          "paginationItemGap": 4,
          "paginationItemBg": "rgba(0,0,0,0.25)",
          "paginationItemActiveBg": "rgba(0,0,0,0.8)",
          "emptyStateId": "spcat_10"
        },
        "specials": {
          "loadMoreLabel": "Load more",
          "collectionIds": []
        },
        "responsive": {
          "tablet": {
            "style": {
              "gap": "20px"
            },
            "config": {
              "itemsPerRow": 2
            }
          },
          "mobile": {
            "style": {
              "gap": "16px"
            },
            "config": {
              "itemsPerRow": 1
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-target",
            "source": "",
            "field": "",
            "target": {
              "type": "product",
              "id": "",
              "kind": "product_list"
            }
          }
        ]
      },
      "spcat_4": {
        "id": "spcat_4",
        "data": {
          "type": "dataset-block",
          "parent": "spcat_3",
          "nodes": [
            "spcat_5",
            "spcat_8",
            "spcat_9"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "gap": "24px",
          "padding": "24px",
          "backgroundColor": "#ffffff",
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "contentWidth": "fill_container",
          "contentWidthCustom": 0,
          "datasetSource": "product"
        },
        "specials": {},
        "responsive": {
          "tablet": {
            "style": {
              "padding": "20px",
              "gap": "20px"
            }
          },
          "mobile": {
            "style": {
              "padding": "16px",
              "gap": "16px"
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-href",
            "source": "product.url",
            "field": "specials.boundHref",
            "target": {
              "type": "product",
              "id": "",
              "kind": "product_general"
            }
          },
          {
            "id": "bind-href-label",
            "source": "product.title",
            "field": "specials.boundHrefLabel"
          }
        ]
      },
      "spcat_5": {
        "id": "spcat_5",
        "data": {
          "type": "media-dataset",
          "parent": "spcat_4",
          "nodes": [
            "spcat_6",
            "spcat_7"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "layout": "bottom",
          "activeIndex": 0
        },
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          }
        ]
      },
      "spcat_6": {
        "id": "spcat_6",
        "data": {
          "type": "product-image-feature",
          "parent": "spcat_5",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "showNav": true,
          "listNavPosition": "inside",
          "listNavButtonWidth": 40,
          "listNavButtonHeight": 40,
          "listNavIconColor": "#000000",
          "listNavButtonBg": "#ffffff",
          "paginationBg": "rgba(0,0,0,0.20)",
          "paginationItemBg": "rgba(255,255,255,0.40)",
          "paginationItemActiveBg": "#FFFFFF",
          "paginationItemWidth": 8,
          "paginationItemHeight": 8,
          "paginationItemGap": 4,
          "featureClickAction": "open_gallery",
          "hoverSwapImage": false,
          "mainImageSource": "first_variant"
        },
        "specials": {
          "alt": ""
        },
        "responsive": {
          "tablet": {
            "config": {
              "listNavButtonWidth": 36,
              "listNavButtonHeight": 36
            }
          },
          "mobile": {
            "config": {
              "listNavButtonWidth": 32,
              "listNavButtonHeight": 32
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          },
          {
            "id": "bind-product-url",
            "source": "product.url",
            "field": "specials.boundProductURL"
          }
        ]
      },
      "spcat_7": {
        "id": "spcat_7",
        "data": {
          "type": "product-image-list",
          "parent": "spcat_5",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "itemSize": 60,
          "gap": 12,
          "listItemImageRatio": "1 / 1",
          "listNavButtonBg": "rgba(255,255,255,0.60)",
          "listNavIconColor": "#000000"
        },
        "specials": {},
        "responsive": {
          "tablet": {
            "config": {
              "itemSize": 52
            }
          },
          "mobile": {
            "config": {
              "itemSize": 44,
              "gap": 8
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "spcat_8": {
        "id": "spcat_8",
        "data": {
          "type": "text-dataset",
          "parent": "spcat_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "20px"
        },
        "config": {
          "datasetSource": "product",
          "kind": "title",
          "textValue": "Product name",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "h4",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "product.title",
            "field": "specials.boundText",
            "target": {
              "type": "product",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "spcat_9": {
        "id": "spcat_9",
        "data": {
          "type": "pricing-dataset",
          "parent": "spcat_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px"
        },
        "config": {
          "kind": "prices",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "prices"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "spcat_10": {
        "id": "spcat_10",
        "data": {
          "type": "list-empty",
          "parent": "spcat_3",
          "nodes": [
            "spcat_11",
            "spcat_12",
            "spcat_13"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "alignItems": "center",
          "justifyContent": "center",
          "gap": "12px",
          "width": "100%",
          "padding": "48px 24px 48px 24px"
        },
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcat_11": {
        "id": "spcat_11",
        "data": {
          "type": "icon",
          "parent": "spcat_10",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "fit-content",
          "height": "fit-content",
          "color": "#d4d4d4"
        },
        "config": {
          "iconSize": 32
        },
        "specials": {
          "name": "ShoppingBag3Line",
          "stylePreset": "icon-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcat_12": {
        "id": "spcat_12",
        "data": {
          "type": "heading",
          "parent": "spcat_10",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "20px",
          "fontWeight": "600",
          "color": "#171717",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "heading-1"
        },
        "specials": {
          "htmlTag": "h3",
          "text": "No products yet",
          "stylePreset": "heading-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcat_13": {
        "id": "spcat_13",
        "data": {
          "type": "text",
          "parent": "spcat_10",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "14px",
          "color": "#737373",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "text": "New arrivals will show up here. Check back soon.",
          "stylePreset": "text-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcat_14": {
        "id": "spcat_14",
        "data": {
          "type": "flex-section",
          "parent": "spcat_1",
          "nodes": [
            "spcat_2",
            "spcat_3"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "width": "100%",
          "height": "fit-content",
          "gap": "24px",
          "paddingTop": "48px",
          "paddingBottom": "48px"
        },
        "config": {},
        "specials": {
          "stylePreset": "container-section"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      }
    }
  },
  "search": {
    "schema_version": 2,
    "root_node_id": "spsea_1",
    "nodes": {
      "spsea_1": {
        "id": "spsea_1",
        "data": {
          "type": "root",
          "parent": null,
          "nodes": [
            "spsea_14"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spsea_2": {
        "id": "spsea_2",
        "data": {
          "type": "search-input",
          "parent": "spsea_14",
          "nodes": [],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "alignItems": "center",
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "iconSize": 18
        },
        "specials": {
          "searchBehavior": "navigate",
          "searchOnEnter": "",
          "searchScope": "page",
          "searchPages": [],
          "searchMinChars": 2,
          "searchPlaceholder": "",
          "searchDebounceMs": 250,
          "searchShowClear": true,
          "searchClearLabel": "Xoá tìm kiếm",
          "searchIconPosition": "start",
          "searchDisplay": "field",
          "searchToggleLabel": "Tìm kiếm",
          "searchClearSwap": false,
          "stylePreset": "search-input-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spsea_3": {
        "id": "spsea_3",
        "data": {
          "type": "list-dataset",
          "parent": "spsea_14",
          "nodes": [
            "spsea_4"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "gap": "24px"
        },
        "config": {
          "datasetSource": "product",
          "articleSourceType": "category",
          "loadingMode": "none",
          "layout": "grid",
          "quantity": 4,
          "itemsPerRow": 4,
          "collectionType": "all_products",
          "collectionId": "all_products",
          "articleCategoryId": "all_articles",
          "collectionListType": "all_collections",
          "listNavIcon": "ArrowLeftSLine",
          "listNavPosition": "inside",
          "listNavIconSize": 16,
          "listNavIconColor": "#171717",
          "listNavButtonWidth": 32,
          "listNavButtonHeight": 32,
          "listNavButtonBg": "#ffffff",
          "paginationItemWidth": 8,
          "paginationItemHeight": 8,
          "paginationItemGap": 4,
          "paginationItemBg": "rgba(0,0,0,0.25)",
          "paginationItemActiveBg": "rgba(0,0,0,0.8)",
          "emptyStateId": "spsea_10"
        },
        "specials": {
          "loadMoreLabel": "Load more",
          "collectionIds": []
        },
        "responsive": {
          "tablet": {
            "style": {
              "gap": "20px"
            },
            "config": {
              "itemsPerRow": 2
            }
          },
          "mobile": {
            "style": {
              "gap": "16px"
            },
            "config": {
              "itemsPerRow": 1
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-target",
            "source": "",
            "field": "",
            "target": {
              "type": "product",
              "id": "",
              "kind": "product_list"
            }
          }
        ]
      },
      "spsea_4": {
        "id": "spsea_4",
        "data": {
          "type": "dataset-block",
          "parent": "spsea_3",
          "nodes": [
            "spsea_5",
            "spsea_8",
            "spsea_9"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "gap": "24px",
          "padding": "24px",
          "backgroundColor": "#ffffff",
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "contentWidth": "fill_container",
          "contentWidthCustom": 0,
          "datasetSource": "product"
        },
        "specials": {},
        "responsive": {
          "tablet": {
            "style": {
              "padding": "20px",
              "gap": "20px"
            }
          },
          "mobile": {
            "style": {
              "padding": "16px",
              "gap": "16px"
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-href",
            "source": "product.url",
            "field": "specials.boundHref",
            "target": {
              "type": "product",
              "id": "",
              "kind": "product_general"
            }
          },
          {
            "id": "bind-href-label",
            "source": "product.title",
            "field": "specials.boundHrefLabel"
          }
        ]
      },
      "spsea_5": {
        "id": "spsea_5",
        "data": {
          "type": "media-dataset",
          "parent": "spsea_4",
          "nodes": [
            "spsea_6",
            "spsea_7"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "layout": "bottom",
          "activeIndex": 0
        },
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          }
        ]
      },
      "spsea_6": {
        "id": "spsea_6",
        "data": {
          "type": "product-image-feature",
          "parent": "spsea_5",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "showNav": true,
          "listNavPosition": "inside",
          "listNavButtonWidth": 40,
          "listNavButtonHeight": 40,
          "listNavIconColor": "#000000",
          "listNavButtonBg": "#ffffff",
          "paginationBg": "rgba(0,0,0,0.20)",
          "paginationItemBg": "rgba(255,255,255,0.40)",
          "paginationItemActiveBg": "#FFFFFF",
          "paginationItemWidth": 8,
          "paginationItemHeight": 8,
          "paginationItemGap": 4,
          "featureClickAction": "open_gallery",
          "hoverSwapImage": false,
          "mainImageSource": "first_variant"
        },
        "specials": {
          "alt": ""
        },
        "responsive": {
          "tablet": {
            "config": {
              "listNavButtonWidth": 36,
              "listNavButtonHeight": 36
            }
          },
          "mobile": {
            "config": {
              "listNavButtonWidth": 32,
              "listNavButtonHeight": 32
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "product.image",
            "field": "specials.boundImage",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          },
          {
            "id": "bind-product-url",
            "source": "product.url",
            "field": "specials.boundProductURL"
          }
        ]
      },
      "spsea_7": {
        "id": "spsea_7",
        "data": {
          "type": "product-image-list",
          "parent": "spsea_5",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%"
        },
        "config": {
          "images": [
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            },
            {
              "src": "",
              "alt": ""
            }
          ],
          "activeIndex": 0,
          "itemSize": 60,
          "gap": 12,
          "listItemImageRatio": "1 / 1",
          "listNavButtonBg": "rgba(255,255,255,0.60)",
          "listNavIconColor": "#000000"
        },
        "specials": {},
        "responsive": {
          "tablet": {
            "config": {
              "itemSize": 52
            }
          },
          "mobile": {
            "config": {
              "itemSize": 44,
              "gap": 8
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-images",
            "source": "product.images",
            "field": "specials.boundImages",
            "target": {
              "type": "product",
              "id": "",
              "kind": "media"
            }
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "spsea_8": {
        "id": "spsea_8",
        "data": {
          "type": "text-dataset",
          "parent": "spsea_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "20px"
        },
        "config": {
          "datasetSource": "product",
          "kind": "title",
          "textValue": "Product name",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "h4",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "product.title",
            "field": "specials.boundText",
            "target": {
              "type": "product",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "spsea_9": {
        "id": "spsea_9",
        "data": {
          "type": "pricing-dataset",
          "parent": "spsea_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "gap": "4px"
        },
        "config": {
          "kind": "prices",
          "priceValue": "$0.00",
          "compareValue": "$0.00",
          "displayPriceId": "both",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-price",
            "source": "product.price",
            "field": "specials.boundPrice",
            "target": {
              "type": "product",
              "id": "",
              "kind": "prices"
            }
          },
          {
            "id": "bind-compare",
            "source": "product.compareAtPrice",
            "field": "specials.boundCompare"
          },
          {
            "id": "bind-price-cents",
            "source": "product.priceCents",
            "field": "specials.boundPriceCents"
          },
          {
            "id": "bind-compare-cents",
            "source": "product.compareAtCents",
            "field": "specials.boundCompareCents"
          },
          {
            "id": "bind-price-mo",
            "source": "product.moneyOverride",
            "field": "specials.boundMoneyOverride"
          },
          {
            "id": "bind-product-id",
            "source": "product.id",
            "field": "specials.boundProductId"
          }
        ]
      },
      "spsea_10": {
        "id": "spsea_10",
        "data": {
          "type": "list-empty",
          "parent": "spsea_3",
          "nodes": [
            "spsea_11",
            "spsea_12",
            "spsea_13"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "alignItems": "center",
          "justifyContent": "center",
          "gap": "12px",
          "width": "100%",
          "padding": "48px 24px 48px 24px"
        },
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spsea_11": {
        "id": "spsea_11",
        "data": {
          "type": "icon",
          "parent": "spsea_10",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "fit-content",
          "height": "fit-content",
          "color": "#d4d4d4"
        },
        "config": {
          "iconSize": 32
        },
        "specials": {
          "name": "ShoppingBag3Line",
          "stylePreset": "icon-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spsea_12": {
        "id": "spsea_12",
        "data": {
          "type": "heading",
          "parent": "spsea_10",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "20px",
          "fontWeight": "600",
          "color": "#171717",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "heading-1"
        },
        "specials": {
          "htmlTag": "h3",
          "text": "No products yet",
          "stylePreset": "heading-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spsea_13": {
        "id": "spsea_13",
        "data": {
          "type": "text",
          "parent": "spsea_10",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "14px",
          "color": "#737373",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "text": "New arrivals will show up here. Check back soon.",
          "stylePreset": "text-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spsea_14": {
        "id": "spsea_14",
        "data": {
          "type": "flex-section",
          "parent": "spsea_1",
          "nodes": [
            "spsea_2",
            "spsea_3"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "width": "100%",
          "height": "fit-content",
          "gap": "24px",
          "paddingTop": "48px",
          "paddingBottom": "48px"
        },
        "config": {},
        "specials": {
          "stylePreset": "container-section"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      }
    }
  },
  "blog": {
    "schema_version": 2,
    "root_node_id": "spblo_1",
    "nodes": {
      "spblo_1": {
        "id": "spblo_1",
        "data": {
          "type": "root",
          "parent": null,
          "nodes": [
            "spblo_13"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spblo_2": {
        "id": "spblo_2",
        "data": {
          "type": "text-dataset",
          "parent": "spblo_13",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "28px"
        },
        "config": {
          "datasetSource": "blogCategory",
          "kind": "title",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "heading-3"
        },
        "specials": {
          "htmlTag": "h3",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "blogCategory.title",
            "field": "specials.boundText",
            "target": {
              "type": "blogCategory",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "spblo_3": {
        "id": "spblo_3",
        "data": {
          "type": "list-dataset",
          "parent": "spblo_13",
          "nodes": [
            "spblo_4"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "gap": "24px"
        },
        "config": {
          "datasetSource": "article",
          "articleSourceType": "category",
          "loadingMode": "none",
          "layout": "grid",
          "quantity": 4,
          "itemsPerRow": 4,
          "collectionType": "all_products",
          "collectionId": "all_products",
          "articleCategoryId": "all_articles",
          "collectionListType": "all_collections",
          "listNavIcon": "ArrowLeftSLine",
          "listNavPosition": "inside",
          "listNavIconSize": 16,
          "listNavIconColor": "#171717",
          "listNavButtonWidth": 32,
          "listNavButtonHeight": 32,
          "listNavButtonBg": "#ffffff",
          "paginationItemWidth": 8,
          "paginationItemHeight": 8,
          "paginationItemGap": 4,
          "paginationItemBg": "rgba(0,0,0,0.25)",
          "paginationItemActiveBg": "rgba(0,0,0,0.8)",
          "emptyStateId": "spblo_9"
        },
        "specials": {
          "loadMoreLabel": "Load more",
          "collectionIds": []
        },
        "responsive": {
          "tablet": {
            "style": {
              "gap": "20px"
            },
            "config": {
              "itemsPerRow": 2
            }
          },
          "mobile": {
            "style": {
              "gap": "16px"
            },
            "config": {
              "itemsPerRow": 1
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-target",
            "source": "",
            "field": "",
            "target": {
              "type": "article",
              "id": "",
              "kind": "article_list"
            }
          }
        ]
      },
      "spblo_4": {
        "id": "spblo_4",
        "data": {
          "type": "dataset-block",
          "parent": "spblo_3",
          "nodes": [
            "spblo_5",
            "spblo_6",
            "spblo_7",
            "spblo_8"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "gap": "24px",
          "padding": "24px",
          "backgroundColor": "#ffffff",
          "width": "100%",
          "height": "fit-content"
        },
        "config": {
          "contentWidth": "fill_container",
          "contentWidthCustom": 0,
          "datasetSource": "article"
        },
        "specials": {},
        "responsive": {
          "tablet": {
            "style": {
              "padding": "20px",
              "gap": "20px"
            }
          },
          "mobile": {
            "style": {
              "padding": "16px",
              "gap": "16px"
            }
          }
        },
        "events": [],
        "bindings": [
          {
            "id": "bind-href",
            "source": "article.url",
            "field": "specials.boundHref",
            "target": {
              "type": "article",
              "id": "",
              "kind": "article_general"
            }
          },
          {
            "id": "bind-href-label",
            "source": "article.title",
            "field": "specials.boundHrefLabel"
          }
        ]
      },
      "spblo_5": {
        "id": "spblo_5",
        "data": {
          "type": "collection-media",
          "parent": "spblo_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "imageRatio": "auto",
          "customImageRatioWidth": 16,
          "customImageRatioHeight": 9,
          "datasetSource": "article"
        },
        "specials": {
          "src": "",
          "alt": ""
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "article.image",
            "field": "specials.boundImage",
            "target": {
              "type": "article",
              "id": "",
              "kind": "media"
            }
          }
        ]
      },
      "spblo_6": {
        "id": "spblo_6",
        "data": {
          "type": "text-dataset",
          "parent": "spblo_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "20px"
        },
        "config": {
          "datasetSource": "article",
          "kind": "title",
          "textValue": "Article title",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "h4",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "article.title",
            "field": "specials.boundText",
            "target": {
              "type": "article",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "spblo_7": {
        "id": "spblo_7",
        "data": {
          "type": "text-dataset",
          "parent": "spblo_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {
          "datasetSource": "article",
          "kind": "summary",
          "textValue": "Article summary",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "article.summary",
            "field": "specials.boundText",
            "target": {
              "type": "article",
              "id": "",
              "kind": "summary"
            }
          }
        ]
      },
      "spblo_8": {
        "id": "spblo_8",
        "data": {
          "type": "text-dataset",
          "parent": "spblo_4",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {
          "datasetSource": "article",
          "kind": "date",
          "textValue": "2026-08-13",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "article.date",
            "field": "specials.boundText",
            "target": {
              "type": "article",
              "id": "",
              "kind": "date"
            }
          }
        ]
      },
      "spblo_9": {
        "id": "spblo_9",
        "data": {
          "type": "list-empty",
          "parent": "spblo_3",
          "nodes": [
            "spblo_10",
            "spblo_11",
            "spblo_12"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "alignItems": "center",
          "justifyContent": "center",
          "gap": "12px",
          "width": "100%",
          "padding": "48px 24px 48px 24px"
        },
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spblo_10": {
        "id": "spblo_10",
        "data": {
          "type": "icon",
          "parent": "spblo_9",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "fit-content",
          "height": "fit-content",
          "color": "#d4d4d4"
        },
        "config": {
          "iconSize": 32
        },
        "specials": {
          "name": "FileListLine",
          "stylePreset": "icon-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spblo_11": {
        "id": "spblo_11",
        "data": {
          "type": "heading",
          "parent": "spblo_9",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "20px",
          "fontWeight": "600",
          "color": "#171717",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "heading-1"
        },
        "specials": {
          "htmlTag": "h3",
          "text": "No posts yet",
          "stylePreset": "heading-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spblo_12": {
        "id": "spblo_12",
        "data": {
          "type": "text",
          "parent": "spblo_9",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "fontSize": "14px",
          "color": "#737373",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "text": "New stories will show up here. Check back soon.",
          "stylePreset": "text-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spblo_13": {
        "id": "spblo_13",
        "data": {
          "type": "flex-section",
          "parent": "spblo_1",
          "nodes": [
            "spblo_2",
            "spblo_3"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "width": "100%",
          "height": "fit-content",
          "gap": "24px",
          "paddingTop": "48px",
          "paddingBottom": "48px"
        },
        "config": {},
        "specials": {
          "stylePreset": "container-section"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      }
    }
  },
  "post": {
    "schema_version": 2,
    "root_node_id": "sppos_1",
    "nodes": {
      "sppos_1": {
        "id": "sppos_1",
        "data": {
          "type": "root",
          "parent": null,
          "nodes": [
            "sppos_6"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "sppos_2": {
        "id": "sppos_2",
        "data": {
          "type": "collection-media",
          "parent": "sppos_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "100%",
          "overflow": "hidden"
        },
        "config": {
          "imageRatio": "auto",
          "customImageRatioWidth": 16,
          "customImageRatioHeight": 9,
          "datasetSource": "article"
        },
        "specials": {
          "src": "",
          "alt": ""
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-image",
            "source": "article.image",
            "field": "specials.boundImage",
            "target": {
              "type": "article",
              "id": "",
              "kind": "media"
            }
          }
        ]
      },
      "sppos_3": {
        "id": "sppos_3",
        "data": {
          "type": "text-dataset",
          "parent": "sppos_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "fontSize": "28px"
        },
        "config": {
          "datasetSource": "article",
          "kind": "title",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "heading-3"
        },
        "specials": {
          "htmlTag": "h3",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "article.title",
            "field": "specials.boundText",
            "target": {
              "type": "article",
              "id": "",
              "kind": "title"
            }
          }
        ]
      },
      "sppos_4": {
        "id": "sppos_4",
        "data": {
          "type": "text-dataset",
          "parent": "sppos_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {
          "datasetSource": "article",
          "kind": "date",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "moreButtonEnabled": false,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "article.date",
            "field": "specials.boundText",
            "target": {
              "type": "article",
              "id": "",
              "kind": "date"
            }
          }
        ]
      },
      "sppos_5": {
        "id": "sppos_5",
        "data": {
          "type": "text-dataset",
          "parent": "sppos_6",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {
          "datasetSource": "article",
          "kind": "description",
          "textValue": "",
          "descriptionDisplayType": "Full",
          "descriptionLines": 3,
          "moreText": "Show more",
          "lessText": "Show less",
          "icon": true,
          "moreButtonColor": "#000000",
          "textGlobalStyle": "text-1"
        },
        "specials": {
          "htmlTag": "p",
          "moreButtonEnabled": true,
          "stylePreset": "text-dataset-default"
        },
        "responsive": {},
        "events": [],
        "bindings": [
          {
            "id": "bind-text",
            "source": "article.content",
            "field": "specials.boundHtml",
            "target": {
              "type": "article",
              "id": "",
              "kind": "description"
            }
          }
        ]
      },
      "sppos_6": {
        "id": "sppos_6",
        "data": {
          "type": "flex-section",
          "parent": "sppos_1",
          "nodes": [
            "sppos_2",
            "sppos_3",
            "sppos_4",
            "sppos_5"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "width": "100%",
          "height": "fit-content",
          "gap": "24px",
          "paddingTop": "48px",
          "paddingBottom": "48px"
        },
        "config": {},
        "specials": {
          "stylePreset": "container-section"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      }
    }
  },
  "complete": {
    "schema_version": 2,
    "root_node_id": "spcom_1",
    "nodes": {
      "spcom_1": {
        "id": "spcom_1",
        "data": {
          "type": "root",
          "parent": null,
          "nodes": [
            "spcom_2"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {},
        "config": {},
        "specials": {},
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcom_2": {
        "id": "spcom_2",
        "data": {
          "type": "flex-section",
          "parent": "spcom_1",
          "nodes": [
            "spcom_3",
            "spcom_4",
            "spcom_5"
          ],
          "isCanvas": true,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "display": "flex",
          "flexDirection": "column",
          "width": "100%",
          "height": "fit-content",
          "alignItems": "center",
          "gap": "16px",
          "paddingTop": "64px",
          "paddingBottom": "64px"
        },
        "config": {},
        "specials": {
          "stylePreset": "container-section"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcom_3": {
        "id": "spcom_3",
        "data": {
          "type": "heading",
          "parent": "spcom_2",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "height": "fit-content",
          "textAlign": "center"
        },
        "config": {
          "textGlobalStyle": "heading-1"
        },
        "specials": {
          "htmlTag": "h2",
          "text": "__SB_COMPLETION_HEADLINE__",
          "stylePreset": "heading-default"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcom_4": {
        "id": "spcom_4",
        "data": {
          "type": "payment-status",
          "parent": "spcom_2",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "maxWidth": "520px"
        },
        "config": {},
        "specials": {
          "paidTitle": "Thanh toán thành công",
          "paidText": "Cảm ơn bạn! Chúng tôi đã nhận được thanh toán và đang xử lý đơn hàng.",
          "pendingTitle": "Đang chờ xác nhận",
          "pendingText": "Chúng tôi chưa nhận được xác nhận từ cổng thanh toán. Đơn hàng sẽ được cập nhật ngay khi có kết quả.",
          "failedTitle": "Thanh toán chưa hoàn tất",
          "failedText": "Giao dịch không thành công hoặc đã bị hủy. Bạn có thể thử lại.",
          "retryLabel": "Thử lại",
          "referenceLabel": "Mã giao dịch"
        },
        "responsive": {},
        "events": [],
        "bindings": []
      },
      "spcom_5": {
        "id": "spcom_5",
        "data": {
          "type": "order-receipt",
          "parent": "spcom_2",
          "nodes": [],
          "isCanvas": false,
          "hidden": false,
          "custom": {}
        },
        "style": {
          "width": "auto",
          "maxWidth": "520px"
        },
        "config": {},
        "specials": {
          "title": "Chi tiết đơn hàng",
          "numberLabel": "Mã đơn hàng",
          "placedLabel": "Ngày đặt",
          "statusLabel": "Trạng thái",
          "itemsLabel": "Sản phẩm",
          "totalLabel": "Tổng cộng",
          "dueLabel": "Còn phải trả",
          "unavailableText": "Không tải được chi tiết đơn hàng. Bạn có thể tra cứu bằng mã đơn hàng trong trang tài khoản."
        },
        "responsive": {},
        "events": [],
        "bindings": []
      }
    }
  }
};
