// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/schema/src/theme.ts (DEFAULT_THEME) and the element metas.
import type { StarterTheme } from './theme-types.js';

export const THEME_SOURCE = {
  "themeVersion": 6,
  "presets": 58,
  "colors": 5,
  "textStyles": 9,
  "schemes": 2,
  "elementsWearingOne": 9
} as const;

export const PRESET_KINDS: string[] = [
  "section",
  "container",
  "heading",
  "bodyText",
  "button",
  "icon",
  "media",
  "divider",
  "field"
];

/**
 * The element type -> style preset its meta.defaults.specials names.
 *
 * createNode already seeds this, so a node minted here wears the right preset.
 * The table exists for the READ side: it says which elements have a style layer
 * their own "style" object does not contain.
 */
export const ELEMENT_PRESETS: Record<string, string> = {
  "flex-section": "container-section",
  "heading": "heading-default",
  "text": "text-default",
  "button": "button-default",
  "image": "image-default",
  "icon": "icon-default",
  "search-input": "search-input-default",
  "quantity-input": "quantity-input-default",
  "text-dataset": "text-dataset-default"
};

/**
 * The STARTER theme — what a site that has never customised its theme resolves
 * against. NOT the authority for a live site: GET /api/sites/{siteId}/theme is,
 * and domains/site/theme.ts prefers it whenever it can be fetched.
 */
export const STARTER_THEME: StarterTheme = {
  "version": 6,
  "colors": [
    {
      "id": "heading",
      "name": "Heading",
      "value": "#111827"
    },
    {
      "id": "text",
      "name": "Text",
      "value": "#374151"
    },
    {
      "id": "primary",
      "name": "Primary",
      "value": "#171717"
    },
    {
      "id": "muted",
      "name": "Muted",
      "value": "#6b7280"
    },
    {
      "id": "background",
      "name": "Background",
      "value": "#ffffff"
    }
  ],
  "textStyles": [
    {
      "slug": "heading-1",
      "name": "Heading 1",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "48px",
        "fontWeight": "700",
        "fontStyle": "normal",
        "lineHeight": "130%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "heading",
        "colorRef": "heading"
      },
      "responsive": {
        "mobile": {
          "fontSize": "32px"
        }
      }
    },
    {
      "slug": "heading-2",
      "name": "Heading 2",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "36px",
        "fontWeight": "700",
        "fontStyle": "normal",
        "lineHeight": "130%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "heading",
        "colorRef": "heading"
      },
      "responsive": {
        "mobile": {
          "fontSize": "28px"
        }
      }
    },
    {
      "slug": "heading-3",
      "name": "Heading 3",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "28px",
        "fontWeight": "600",
        "fontStyle": "normal",
        "lineHeight": "130%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "heading",
        "colorRef": "heading"
      },
      "responsive": {
        "mobile": {
          "fontSize": "24px"
        }
      }
    },
    {
      "slug": "heading-4",
      "name": "Heading 4",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "22px",
        "fontWeight": "600",
        "fontStyle": "normal",
        "lineHeight": "130%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "heading",
        "colorRef": "heading"
      }
    },
    {
      "slug": "heading-5",
      "name": "Heading 5",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "18px",
        "fontWeight": "600",
        "fontStyle": "normal",
        "lineHeight": "130%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "heading",
        "colorRef": "heading"
      }
    },
    {
      "slug": "heading-6",
      "name": "Heading 6",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "16px",
        "fontWeight": "600",
        "fontStyle": "normal",
        "lineHeight": "130%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "heading",
        "colorRef": "heading"
      }
    },
    {
      "slug": "text-1",
      "name": "Text 1",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "16px",
        "fontWeight": "400",
        "fontStyle": "normal",
        "lineHeight": "140%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "text",
        "colorRef": "text"
      }
    },
    {
      "slug": "text-2",
      "name": "Text 2",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "14px",
        "fontWeight": "400",
        "fontStyle": "normal",
        "lineHeight": "140%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "text",
        "colorRef": "text"
      }
    },
    {
      "slug": "text-3",
      "name": "Text 3",
      "base": {
        "fontFamily": "Inter",
        "fontSize": "12px",
        "fontWeight": "400",
        "fontStyle": "normal",
        "lineHeight": "140%",
        "letterSpacing": "normal",
        "textTransform": "none",
        "colorRole": "text",
        "colorRef": "text"
      }
    }
  ],
  "schemes": [
    {
      "id": "light",
      "name": "Light",
      "roles": {
        "background": "var(--wb-color-background)",
        "text": "var(--wb-color-text)",
        "heading": "var(--wb-color-heading)",
        "link": "var(--wb-color-primary)",
        "buttonBg": "var(--wb-color-primary)",
        "buttonText": "#ffffff",
        "border": "#e5e7eb",
        "shadow": "rgba(17,24,39,0.08)"
      }
    },
    {
      "id": "dark",
      "name": "Dark",
      "roles": {
        "background": "#111827",
        "text": "#d1d5db",
        "heading": "#ffffff",
        "link": "#ffffff",
        "buttonBg": "#ffffff",
        "buttonText": "#111827",
        "border": "rgba(255,255,255,0.16)",
        "shadow": "rgba(0,0,0,0.4)"
      }
    }
  ],
  "lightSchemeId": "light",
  "presets": [
    {
      "id": "button-default",
      "name": "Default",
      "kind": "button",
      "base": {
        "backgroundColor": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "color": "var(--wb-sc-buttonText, var(--wb-color-background))",
        "padding": "10px 24px",
        "textAlign": "center",
        "fontSize": "14px",
        "fontFamily": "Inter",
        "lineHeight": "20px"
      },
      "responsive": {
        "mobile": {
          "padding": "10px 18px"
        }
      }
    },
    {
      "id": "button-primary",
      "name": "Primary",
      "kind": "button",
      "base": {
        "backgroundColor": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "color": "var(--wb-sc-buttonText, var(--wb-color-background))",
        "borderRadius": "8px",
        "padding": "12px 24px",
        "fontWeight": "600"
      },
      "responsive": {
        "mobile": {
          "padding": "10px 18px"
        }
      }
    },
    {
      "id": "button-outline",
      "name": "Outline",
      "kind": "button",
      "base": {
        "backgroundColor": "transparent",
        "color": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "border": "1px solid var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "borderRadius": "8px",
        "padding": "11px 23px",
        "fontWeight": "600"
      },
      "responsive": {
        "mobile": {
          "padding": "9px 17px"
        }
      }
    },
    {
      "id": "button-pill",
      "name": "Pill",
      "kind": "button",
      "base": {
        "backgroundColor": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "color": "var(--wb-sc-buttonText, var(--wb-color-background))",
        "borderRadius": "999px",
        "padding": "12px 28px",
        "fontWeight": "600"
      },
      "responsive": {
        "mobile": {
          "padding": "10px 20px"
        }
      }
    },
    {
      "id": "button-soft",
      "name": "Soft",
      "kind": "button",
      "base": {
        "backgroundColor": "var(--wb-sc-border, var(--wb-color-muted))",
        "color": "var(--wb-sc-heading, var(--wb-color-heading))",
        "borderRadius": "8px",
        "padding": "12px 24px",
        "fontWeight": "600"
      },
      "responsive": {
        "mobile": {
          "padding": "10px 18px"
        }
      }
    },
    {
      "id": "button-text",
      "name": "Text link",
      "kind": "button",
      "base": {
        "backgroundColor": "transparent",
        "color": "var(--wb-sc-link, var(--wb-color-primary))",
        "padding": "8px 4px",
        "fontWeight": "600",
        "textDecoration": "underline"
      }
    },
    {
      "id": "button-cta",
      "name": "Large CTA",
      "kind": "button",
      "base": {
        "backgroundColor": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "color": "var(--wb-sc-buttonText, var(--wb-color-background))",
        "borderRadius": "10px",
        "padding": "18px 40px",
        "fontWeight": "700"
      },
      "responsive": {
        "mobile": {
          "padding": "16px 24px",
          "width": "100%"
        }
      }
    },
    {
      "id": "container-section",
      "name": "Section",
      "kind": "section",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "padding": "64px 24px",
        "--wb-content-max": "1440px"
      },
      "responsive": {
        "tablet": {
          "padding": "48px 20px"
        },
        "mobile": {
          "padding": "32px 16px"
        }
      }
    },
    {
      "id": "section-narrow",
      "name": "Narrow",
      "kind": "section",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "padding": "64px 24px",
        "--wb-content-max": "760px"
      },
      "responsive": {
        "tablet": {
          "padding": "48px 20px"
        },
        "mobile": {
          "padding": "32px 16px"
        }
      }
    },
    {
      "id": "section-wide",
      "name": "Full width",
      "kind": "section",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "padding": "0px",
        "--wb-content-max": "none"
      }
    },
    {
      "id": "section-muted",
      "name": "Muted",
      "kind": "section",
      "base": {
        "backgroundColor": "var(--wb-sc-border, var(--wb-color-muted))",
        "padding": "64px 24px",
        "--wb-content-max": "1440px"
      },
      "responsive": {
        "tablet": {
          "padding": "48px 20px"
        },
        "mobile": {
          "padding": "32px 16px"
        }
      }
    },
    {
      "id": "section-compact",
      "name": "Compact",
      "kind": "section",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "padding": "24px",
        "--wb-content-max": "1440px"
      },
      "responsive": {
        "mobile": {
          "padding": "16px"
        }
      }
    },
    {
      "id": "container-card",
      "name": "Card",
      "kind": "container",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "border": "1px solid var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "12px",
        "padding": "24px"
      },
      "responsive": {
        "mobile": {
          "padding": "16px",
          "borderRadius": "10px"
        }
      }
    },
    {
      "id": "container-panel",
      "name": "Panel",
      "kind": "container",
      "base": {
        "backgroundColor": "var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "12px",
        "padding": "24px"
      },
      "responsive": {
        "mobile": {
          "padding": "16px"
        }
      }
    },
    {
      "id": "container-elevated",
      "name": "Elevated",
      "kind": "container",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "borderRadius": "14px",
        "padding": "28px",
        "boxShadow": "0 6px 24px var(--wb-sc-shadow, var(--wb-color-muted))"
      },
      "responsive": {
        "mobile": {
          "padding": "18px",
          "borderRadius": "12px"
        }
      }
    },
    {
      "id": "container-hero",
      "name": "Hero",
      "kind": "section",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "padding": "112px 24px",
        "textAlign": "center"
      },
      "responsive": {
        "tablet": {
          "padding": "80px 20px"
        },
        "mobile": {
          "padding": "56px 16px"
        }
      }
    },
    {
      "id": "container-narrow",
      "name": "Narrow",
      "kind": "container",
      "base": {
        "maxWidth": "760px",
        "marginLeft": "auto",
        "marginRight": "auto",
        "padding": "0 24px"
      },
      "responsive": {
        "mobile": {
          "padding": "0 16px"
        }
      }
    },
    {
      "id": "container-outline",
      "name": "Outline",
      "kind": "container",
      "base": {
        "border": "1px solid var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "12px",
        "padding": "24px"
      },
      "responsive": {
        "mobile": {
          "padding": "16px",
          "borderRadius": "10px"
        }
      }
    },
    {
      "id": "heading-default",
      "name": "Default",
      "kind": "heading",
      "base": {
        "textAlign": "left",
        "lineHeight": "130%",
        "fontFamily": "Inter",
        "fontSize": "48px",
        "color": "var(--wb-sc-heading, var(--wb-color-heading))"
      },
      "responsive": {
        "tablet": {
          "fontSize": "40px"
        },
        "mobile": {
          "fontSize": "30px"
        }
      }
    },
    {
      "id": "heading-section",
      "name": "Section title",
      "kind": "heading",
      "base": {
        "color": "var(--wb-sc-heading, var(--wb-color-heading))",
        "textAlign": "center",
        "marginBottom": "16px"
      }
    },
    {
      "id": "heading-page",
      "name": "Page title",
      "kind": "heading",
      "base": {
        "color": "var(--wb-sc-heading, var(--wb-color-heading))",
        "textAlign": "left",
        "marginBottom": "24px"
      },
      "responsive": {
        "mobile": {
          "marginBottom": "16px"
        }
      }
    },
    {
      "id": "heading-eyebrow",
      "name": "Eyebrow",
      "kind": "heading",
      "base": {
        "color": "var(--wb-sc-link, var(--wb-color-primary))",
        "textTransform": "uppercase",
        "letterSpacing": "0.08em",
        "marginBottom": "8px"
      }
    },
    {
      "id": "heading-subtle",
      "name": "Subtle",
      "kind": "heading",
      "base": {
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "marginBottom": "12px"
      }
    },
    {
      "id": "heading-accent",
      "name": "Accent",
      "kind": "heading",
      "base": {
        "color": "var(--wb-sc-accent1, var(--wb-color-primary))",
        "textAlign": "center",
        "marginBottom": "16px"
      }
    },
    {
      "id": "heading-underlined",
      "name": "Underlined",
      "kind": "heading",
      "base": {
        "color": "var(--wb-sc-heading, var(--wb-color-heading))",
        "borderBottom": "2px solid var(--wb-sc-border, var(--wb-color-muted))",
        "paddingBottom": "12px",
        "marginBottom": "20px"
      }
    },
    {
      "id": "text-default",
      "name": "Default",
      "kind": "bodyText",
      "base": {
        "textAlign": "left",
        "lineHeight": "140%",
        "fontFamily": "Inter",
        "fontSize": "16px",
        "color": "var(--wb-sc-text, var(--wb-color-text))"
      }
    },
    {
      "id": "text-dataset-default",
      "name": "Default (dynamic)",
      "kind": "bodyText",
      "base": {
        "textAlign": "left",
        "lineHeight": "140%",
        "fontFamily": "Inter",
        "fontSize": "16px",
        "color": "var(--wb-sc-text, var(--wb-color-text))"
      }
    },
    {
      "id": "body-lead",
      "name": "Lead",
      "kind": "bodyText",
      "base": {
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "textAlign": "center",
        "maxWidth": "640px"
      }
    },
    {
      "id": "body-default",
      "name": "Body",
      "kind": "bodyText",
      "base": {
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "maxWidth": "680px"
      }
    },
    {
      "id": "body-muted",
      "name": "Muted",
      "kind": "bodyText",
      "base": {
        "color": "var(--wb-sc-border, var(--wb-color-muted))",
        "maxWidth": "680px"
      }
    },
    {
      "id": "body-centered",
      "name": "Centered",
      "kind": "bodyText",
      "base": {
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "textAlign": "center",
        "maxWidth": "560px",
        "marginLeft": "auto",
        "marginRight": "auto"
      }
    },
    {
      "id": "body-note",
      "name": "Note",
      "kind": "bodyText",
      "base": {
        "color": "var(--wb-sc-border, var(--wb-color-muted))",
        "marginTop": "8px"
      }
    },
    {
      "id": "body-quote",
      "name": "Quote",
      "kind": "bodyText",
      "base": {
        "color": "var(--wb-sc-heading, var(--wb-color-heading))",
        "borderLeft": "3px solid var(--wb-sc-accent1, var(--wb-color-primary))",
        "paddingLeft": "16px",
        "fontStyle": "italic"
      }
    },
    {
      "id": "icon-default",
      "name": "Default",
      "kind": "icon",
      "base": {
        "color": "var(--wb-sc-heading, var(--wb-color-heading))"
      }
    },
    {
      "id": "icon-badge",
      "name": "Badge",
      "kind": "icon",
      "base": {
        "color": "var(--wb-sc-buttonText, var(--wb-color-background))",
        "backgroundColor": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "borderRadius": "999px",
        "padding": "8px"
      }
    },
    {
      "id": "icon-outline",
      "name": "Outline",
      "kind": "icon",
      "base": {
        "color": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "borderRadius": "999px",
        "padding": "8px"
      }
    },
    {
      "id": "icon-soft",
      "name": "Soft",
      "kind": "icon",
      "base": {
        "color": "var(--wb-sc-heading, var(--wb-color-heading))",
        "backgroundColor": "var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "999px",
        "padding": "8px"
      }
    },
    {
      "id": "icon-square",
      "name": "Square",
      "kind": "icon",
      "base": {
        "color": "var(--wb-sc-buttonText, var(--wb-color-background))",
        "backgroundColor": "var(--wb-sc-buttonBg, var(--wb-color-primary))",
        "borderRadius": "8px",
        "padding": "8px"
      }
    },
    {
      "id": "icon-plain",
      "name": "Plain",
      "kind": "icon",
      "base": {
        "color": "var(--wb-sc-heading, var(--wb-color-heading))"
      }
    },
    {
      "id": "icon-accent",
      "name": "Accent",
      "kind": "icon",
      "base": {
        "color": "var(--wb-sc-accent1, var(--wb-color-primary))"
      }
    },
    {
      "id": "image-default",
      "name": "Default",
      "kind": "media",
      "base": {
        "objectFit": "cover",
        "objectPosition": "top left"
      }
    },
    {
      "id": "media-rounded",
      "name": "Rounded",
      "kind": "media",
      "base": {
        "borderRadius": "12px",
        "overflow": "hidden"
      },
      "responsive": {
        "mobile": {
          "borderRadius": "8px"
        }
      }
    },
    {
      "id": "media-circle",
      "name": "Circle",
      "kind": "media",
      "base": {
        "borderRadius": "999px",
        "overflow": "hidden"
      }
    },
    {
      "id": "media-square",
      "name": "Square",
      "kind": "media",
      "base": {
        "borderRadius": "0px",
        "overflow": "hidden"
      }
    },
    {
      "id": "media-card",
      "name": "Card",
      "kind": "media",
      "base": {
        "borderRadius": "12px",
        "overflow": "hidden",
        "boxShadow": "0 6px 24px var(--wb-sc-shadow, var(--wb-color-muted))"
      },
      "responsive": {
        "mobile": {
          "borderRadius": "10px"
        }
      }
    },
    {
      "id": "media-bordered",
      "name": "Bordered",
      "kind": "media",
      "base": {
        "borderRadius": "12px",
        "overflow": "hidden",
        "border": "1px solid var(--wb-sc-border, var(--wb-color-muted))"
      }
    },
    {
      "id": "media-framed",
      "name": "Framed",
      "kind": "media",
      "base": {
        "borderRadius": "12px",
        "overflow": "hidden",
        "border": "8px solid var(--wb-sc-background, var(--wb-color-background))",
        "boxShadow": "0 2px 10px var(--wb-sc-shadow, var(--wb-color-muted))"
      },
      "responsive": {
        "mobile": {
          "border": "4px solid var(--wb-sc-background, var(--wb-color-background))"
        }
      }
    },
    {
      "id": "divider-hairline",
      "name": "Hairline",
      "kind": "divider",
      "base": {
        "--wb-divider-thickness": "1px",
        "--wb-divider-style": "solid",
        "--wb-divider-color": "var(--wb-sc-border, var(--wb-color-muted))"
      }
    },
    {
      "id": "divider-thick",
      "name": "Thick",
      "kind": "divider",
      "base": {
        "--wb-divider-thickness": "3px",
        "--wb-divider-style": "solid",
        "--wb-divider-color": "var(--wb-sc-border, var(--wb-color-muted))"
      }
    },
    {
      "id": "divider-dashed",
      "name": "Dashed",
      "kind": "divider",
      "base": {
        "--wb-divider-thickness": "1px",
        "--wb-divider-style": "dashed",
        "--wb-divider-color": "var(--wb-sc-border, var(--wb-color-muted))"
      }
    },
    {
      "id": "quantity-input-default",
      "name": "Default (quantity)",
      "kind": "field",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))"
      }
    },
    {
      "id": "search-input-default",
      "name": "Default (search)",
      "kind": "field",
      "base": {
        "gap": "8px",
        "padding": "10px 14px",
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "borderRadius": "8px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "var(--wb-sc-border, var(--wb-color-muted))"
      }
    },
    {
      "id": "field-boxed",
      "name": "Boxed",
      "kind": "field",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "border": "1px solid var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "8px",
        "padding": "10px 12px"
      }
    },
    {
      "id": "field-rounded",
      "name": "Rounded",
      "kind": "field",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "border": "1px solid var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "999px",
        "padding": "10px 18px"
      }
    },
    {
      "id": "field-underline",
      "name": "Underline",
      "kind": "field",
      "base": {
        "backgroundColor": "transparent",
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "borderBottom": "1px solid var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "0px",
        "padding": "10px 2px"
      }
    },
    {
      "id": "field-soft",
      "name": "Soft",
      "kind": "field",
      "base": {
        "backgroundColor": "var(--wb-sc-border, var(--wb-color-muted))",
        "color": "var(--wb-sc-heading, var(--wb-color-heading))",
        "borderRadius": "8px",
        "padding": "10px 12px"
      }
    },
    {
      "id": "field-large",
      "name": "Large",
      "kind": "field",
      "base": {
        "backgroundColor": "var(--wb-sc-background, var(--wb-color-background))",
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "border": "1px solid var(--wb-sc-border, var(--wb-color-muted))",
        "borderRadius": "10px",
        "padding": "16px 18px"
      },
      "responsive": {
        "mobile": {
          "padding": "13px 14px"
        }
      }
    },
    {
      "id": "field-minimal",
      "name": "Minimal",
      "kind": "field",
      "base": {
        "backgroundColor": "transparent",
        "color": "var(--wb-sc-text, var(--wb-color-text))",
        "padding": "10px 2px"
      }
    }
  ]
};
