// GENERATED by scripts/gen-catalog.ts — do not edit by hand.
// Source: <WB_REPO>/schema/src/elements/translatableFields.ts

export const TRANSLATION_SOURCE = {
  "elements": 67,
  "pairs": 187,
  "neverKeys": 180,
  "entityTypes": 11
} as const;

/** Every entity type a translation record can name, including "node". */
export const TRANSLATION_ENTITY_TYPES: string[] = [
  "product",
  "category",
  "article",
  "blogCategory",
  "course",
  "courseSection",
  "courseLesson",
  "node",
  "page",
  "uiString",
  "mailString",
  "siteLabel"
];

/**
 * The specials a translation MAY rewrite, per element type.
 *
 * An element absent here has none. That is not an oversight: an icon's only
 * string is a lucide id.
 */
export const TRANSLATABLE_SPECIALS: Record<string, string[]> = {
  "popup": [
    "closeLabel"
  ],
  "select": [
    "placeholder",
    "filterValues"
  ],
  "filter-checkbox": [
    "filterValues",
    "filterAllLabel"
  ],
  "filter-radio": [
    "filterValues",
    "filterAllLabel"
  ],
  "filter-color": [
    "filterValues",
    "filterAllLabel"
  ],
  "filter-tag": [
    "filterValues",
    "filterAllLabel"
  ],
  "account-info": [
    "promptText",
    "loginLabel"
  ],
  "cart-count": [
    "placeholder"
  ],
  "cart-total": [
    "label",
    "placeholder"
  ],
  "free-ship-bar": [
    "remainingText",
    "reachedText"
  ],
  "flash-sale-progress": [
    "soldText",
    "almostText",
    "soldOutText"
  ],
  "voucher-list": [
    "title",
    "buttonLabel",
    "emptyText",
    "copiedText",
    "failedText"
  ],
  "countdown": [
    "expiredText",
    "dayLabel",
    "hourLabel",
    "minuteLabel",
    "secondLabel"
  ],
  "order-history": [
    "title",
    "emptyText",
    "signedOutText",
    "lookupNumberPlaceholder",
    "lookupContactPlaceholder",
    "lookupButtonText"
  ],
  "order-receipt": [
    "title",
    "numberLabel",
    "placedLabel",
    "statusLabel",
    "itemsLabel",
    "totalLabel",
    "dueLabel",
    "unavailableText"
  ],
  "course-outline": [
    "emptyText"
  ],
  "my-courses": [
    "emptyText",
    "signedOutText",
    "continueText"
  ],
  "course-player": [
    "completeLabel",
    "completedLabel",
    "certificateText",
    "lockedText",
    "lockedLabel",
    "emptyText"
  ],
  "wishlist-list": [
    "title",
    "emptyText"
  ],
  "address-book": [
    "title",
    "emptyText",
    "signedOutText",
    "addLabel"
  ],
  "points-card": [
    "title",
    "signedOutText"
  ],
  "my-vouchers": [
    "title",
    "signedOutText",
    "buttonLabel",
    "emptyText",
    "copiedText",
    "failedText",
    "loadFailedText",
    "usedText",
    "expiredText"
  ],
  "my-tickets": [
    "title",
    "signedOutText",
    "buttonLabel",
    "emptyText",
    "loadFailedText",
    "usedText",
    "voidText"
  ],
  "member-field": [
    "prefix",
    "suffix",
    "guestText"
  ],
  "accordion-content": [
    "label"
  ],
  "button": [
    "text",
    "textHtml"
  ],
  "cart-order": [
    "emptyText"
  ],
  "payment-status": [
    "paidTitle",
    "paidText",
    "pendingTitle",
    "pendingText",
    "failedTitle",
    "failedText",
    "retryLabel",
    "referenceLabel"
  ],
  "collection-media": [
    "alt"
  ],
  "divider": [
    "label"
  ],
  "heading": [
    "text",
    "textHtml"
  ],
  "form-text": [
    "label",
    "placeholder",
    "description"
  ],
  "form-number": [
    "label",
    "placeholder",
    "description"
  ],
  "form-select": [
    "label",
    "options",
    "placeholder",
    "description"
  ],
  "form-address": [
    "label",
    "description",
    "provinceLabel",
    "wardLabel",
    "detailLabel",
    "provincePlaceholder",
    "wardPlaceholder",
    "detailPlaceholder",
    "placeholder"
  ],
  "form-discount-code": [
    "label",
    "placeholder",
    "description",
    "buttonLabel",
    "appliedText",
    "unknownCodeText",
    "codeNotUsableText",
    "quoteFailedText"
  ],
  "form-radio": [
    "label",
    "options",
    "description"
  ],
  "form-payment": [
    "label",
    "description",
    "methods"
  ],
  "form-timeslot": [
    "label",
    "description"
  ],
  "form-checkbox": [
    "label",
    "options",
    "description"
  ],
  "form-date": [
    "label",
    "description",
    "dayPlaceholder",
    "monthPlaceholder",
    "yearPlaceholder",
    "dayLabel",
    "monthLabel",
    "yearLabel",
    "timeLabel"
  ],
  "form-calendar": [
    "label",
    "description"
  ],
  "form-file": [
    "label",
    "placeholder",
    "hintText",
    "description",
    "buttonLabel"
  ],
  "form-paragraph": [
    "text"
  ],
  "form-link": [
    "text",
    "linkText"
  ],
  "form-step-button": [
    "text"
  ],
  "form-submit": [
    "text",
    "submittingText"
  ],
  "form-title": [
    "text"
  ],
  "image": [
    "alt"
  ],
  "image-comparison": [
    "beforeAlt",
    "afterAlt"
  ],
  "list-dataset": [
    "loadMoreLabel"
  ],
  "list-item": [
    "text"
  ],
  "product-image-feature": [
    "alt"
  ],
  "search-input": [
    "searchPlaceholder",
    "searchClearLabel",
    "searchToggleLabel"
  ],
  "tab-content": [
    "label"
  ],
  "text": [
    "text",
    "textHtml"
  ],
  "text-marquee": [
    "text"
  ],
  "text-marquee-item": [
    "text"
  ],
  "breadcrumb": [
    "crumbs",
    "homeLabel"
  ],
  "menu": [
    "menuItems"
  ],
  "chat-widget": [
    "title",
    "launcherText"
  ],
  "qr-code": [
    "alt",
    "value"
  ],
  "bundle-items": [
    "heading",
    "quantitySeparator"
  ],
  "search-keywords": [
    "keywordItems"
  ],
  "locale-switcher": [
    "panelTitle"
  ],
  "theme-switcher": [
    "lightLabel",
    "darkLabel"
  ],
  "sale-badge": [
    "text"
  ]
};

/**
 * Specials keys that must NEVER be translated, across every element.
 *
 * Translating one of these does not degrade the page — it BREAKS the render.
 * Kept as the platform's whole classification rather than an allow-list,
 * because a positive-only list goes stale silently as elements ship new strings.
 */
export const NEVER_TRANSLATED: string[] = [
  "acceptedDates",
  "addressGroup",
  "addressLink",
  "afterSrc",
  "allowMultiple",
  "allowedCodes",
  "arrow",
  "audience",
  "authKind",
  "autoComplete",
  "availableDays",
  "beforeSrc",
  "bookMaxDays",
  "bookMinDays",
  "bookSlots",
  "bookingHost",
  "boundBundleItems",
  "boundCompareCents",
  "boundHref",
  "boundHrefLabel",
  "boundModel",
  "boundMoneyOverride",
  "boundPriceCents",
  "boundProductURL",
  "boundValue",
  "breakEnd",
  "breakStart",
  "button",
  "capturesProduct",
  "className",
  "closeIcon",
  "code",
  "collectionIds",
  "contentType",
  "copyFrom",
  "country",
  "courseId",
  "customCss",
  "customName",
  "ddFilterSource",
  "ddFilterStash",
  "ddSortStash",
  "defaultMode",
  "defaultVariant",
  "dir",
  "displayType",
  "end",
  "endsAt",
  "field",
  "fileFormat",
  "fileLimit",
  "filterArity",
  "filterAxis",
  "filterBehavior",
  "filterColors",
  "filterExcluded",
  "filterHierarchy",
  "filterMatch",
  "filterMaxDepth",
  "filterMaxValues",
  "filterRanges",
  "filterShowAll",
  "filterShowCount",
  "filterSource",
  "filterTarget",
  "filterTargets",
  "filterValueMode",
  "filterable",
  "formId",
  "formRules",
  "format",
  "hideOnPage",
  "hideWhenEmpty",
  "hoverHostDepth",
  "href",
  "htmlTag",
  "icon",
  "iconEnabled",
  "iconName",
  "inputType",
  "keywordAction",
  "kind",
  "labelMode",
  "launcherIcon",
  "learnHref",
  "limitChars",
  "linkTarget",
  "lockedHref",
  "loginHref",
  "logoShape",
  "lookupEnabled",
  "mapTo",
  "mapType",
  "maxCents",
  "maxChars",
  "maxLabelText",
  "maxValue",
  "menuId",
  "minCents",
  "minChars",
  "minLabelText",
  "minValue",
  "mode",
  "modelUrl",
  "moneyPayload",
  "moreButtonEnabled",
  "multiline",
  "name",
  "openOnHover",
  "orderSource",
  "orientation",
  "overlayId",
  "part",
  "parts",
  "pattern",
  "patternCountries",
  "patternPreset",
  "payload",
  "picker",
  "poster",
  "posterUrl",
  "prefillValue",
  "presetCode",
  "provinceField",
  "ratingValue",
  "required",
  "reviewForm",
  "sameDefault",
  "sceneControls",
  "sceneGallery",
  "sceneUrl",
  "sceneViewer",
  "searchBehavior",
  "searchClearSwap",
  "searchDebounceMs",
  "searchDisplay",
  "searchIconPosition",
  "searchMinChars",
  "searchOnEnter",
  "searchPages",
  "searchScope",
  "searchShowClear",
  "searchTargets",
  "searchable",
  "segmentId",
  "selectMode",
  "sentRedirect",
  "sentText",
  "setRange",
  "showCount",
  "showCountdown",
  "showCurrent",
  "showDetail",
  "showFlag",
  "showHeading",
  "showIcon",
  "showLabel",
  "showLogos",
  "showMarker",
  "showOutline",
  "showPercent",
  "showPhone",
  "showPlaceholder",
  "source",
  "sourceCode",
  "sourceFlashSale",
  "specificDate",
  "src",
  "start",
  "step",
  "stepMode",
  "stylePreset",
  "symbolChar",
  "target",
  "thresholdCents",
  "trackUrl",
  "urlParam",
  "variant",
  "videoId",
  "videoSrc"
];

/** One translatable field, as the editor's page collector reads it. */
export interface TranslatableFieldSpec {
  key: string;
  /** Reaches a raw HTML sink: a machine fill skips it, a human writes it. */
  html?: true;
  /**
   * One row per item: `strings`/`labels` address `<key>.<base text>`, the
   * object form `<key>.<item id>.<textKey>` (nested `items` walked too).
   */
  list?: 'strings' | 'labels' | 'attributes' | { itemIdKey: string; textKey: string | string[] };
  /** Translatable only while `specials[when.key] === when.equals`. */
  when?: { key: string; equals: string };
}

/** Every translatable special per element, with its shape. */
export const TRANSLATABLE_FIELDS: Record<string, TranslatableFieldSpec[]> = {
  "popup": [
    {
      "key": "closeLabel"
    }
  ],
  "select": [
    {
      "key": "placeholder"
    },
    {
      "key": "filterValues",
      "list": {
        "itemIdKey": "value",
        "textKey": "label"
      }
    }
  ],
  "filter-checkbox": [
    {
      "key": "filterValues",
      "list": {
        "itemIdKey": "value",
        "textKey": "label"
      }
    },
    {
      "key": "filterAllLabel"
    }
  ],
  "filter-radio": [
    {
      "key": "filterValues",
      "list": {
        "itemIdKey": "value",
        "textKey": "label"
      }
    },
    {
      "key": "filterAllLabel"
    }
  ],
  "filter-color": [
    {
      "key": "filterValues",
      "list": {
        "itemIdKey": "value",
        "textKey": "label"
      }
    },
    {
      "key": "filterAllLabel"
    }
  ],
  "filter-tag": [
    {
      "key": "filterValues",
      "list": {
        "itemIdKey": "value",
        "textKey": "label"
      }
    },
    {
      "key": "filterAllLabel"
    }
  ],
  "account-info": [
    {
      "key": "promptText"
    },
    {
      "key": "loginLabel"
    }
  ],
  "cart-count": [
    {
      "key": "placeholder"
    }
  ],
  "cart-total": [
    {
      "key": "label"
    },
    {
      "key": "placeholder"
    }
  ],
  "free-ship-bar": [
    {
      "key": "remainingText"
    },
    {
      "key": "reachedText"
    }
  ],
  "flash-sale-progress": [
    {
      "key": "soldText"
    },
    {
      "key": "almostText"
    },
    {
      "key": "soldOutText"
    }
  ],
  "voucher-list": [
    {
      "key": "title"
    },
    {
      "key": "buttonLabel"
    },
    {
      "key": "emptyText"
    },
    {
      "key": "copiedText"
    },
    {
      "key": "failedText"
    }
  ],
  "countdown": [
    {
      "key": "expiredText"
    },
    {
      "key": "dayLabel"
    },
    {
      "key": "hourLabel"
    },
    {
      "key": "minuteLabel"
    },
    {
      "key": "secondLabel"
    }
  ],
  "order-history": [
    {
      "key": "title"
    },
    {
      "key": "emptyText"
    },
    {
      "key": "signedOutText"
    },
    {
      "key": "lookupNumberPlaceholder"
    },
    {
      "key": "lookupContactPlaceholder"
    },
    {
      "key": "lookupButtonText"
    }
  ],
  "order-receipt": [
    {
      "key": "title"
    },
    {
      "key": "numberLabel"
    },
    {
      "key": "placedLabel"
    },
    {
      "key": "statusLabel"
    },
    {
      "key": "itemsLabel"
    },
    {
      "key": "totalLabel"
    },
    {
      "key": "dueLabel"
    },
    {
      "key": "unavailableText"
    }
  ],
  "course-outline": [
    {
      "key": "emptyText"
    }
  ],
  "my-courses": [
    {
      "key": "emptyText"
    },
    {
      "key": "signedOutText"
    },
    {
      "key": "continueText"
    }
  ],
  "course-player": [
    {
      "key": "completeLabel"
    },
    {
      "key": "completedLabel"
    },
    {
      "key": "certificateText"
    },
    {
      "key": "lockedText"
    },
    {
      "key": "lockedLabel"
    },
    {
      "key": "emptyText"
    }
  ],
  "wishlist-list": [
    {
      "key": "title"
    },
    {
      "key": "emptyText"
    }
  ],
  "address-book": [
    {
      "key": "title"
    },
    {
      "key": "emptyText"
    },
    {
      "key": "signedOutText"
    },
    {
      "key": "addLabel"
    }
  ],
  "points-card": [
    {
      "key": "title"
    },
    {
      "key": "signedOutText"
    }
  ],
  "my-vouchers": [
    {
      "key": "title"
    },
    {
      "key": "signedOutText"
    },
    {
      "key": "buttonLabel"
    },
    {
      "key": "emptyText"
    },
    {
      "key": "copiedText"
    },
    {
      "key": "failedText"
    },
    {
      "key": "loadFailedText"
    },
    {
      "key": "usedText"
    },
    {
      "key": "expiredText"
    }
  ],
  "my-tickets": [
    {
      "key": "title"
    },
    {
      "key": "signedOutText"
    },
    {
      "key": "buttonLabel"
    },
    {
      "key": "emptyText"
    },
    {
      "key": "loadFailedText"
    },
    {
      "key": "usedText"
    },
    {
      "key": "voidText"
    }
  ],
  "member-field": [
    {
      "key": "prefix"
    },
    {
      "key": "suffix"
    },
    {
      "key": "guestText"
    }
  ],
  "accordion-content": [
    {
      "key": "label"
    }
  ],
  "button": [
    {
      "key": "text"
    },
    {
      "key": "textHtml",
      "html": true
    }
  ],
  "cart-order": [
    {
      "key": "emptyText"
    }
  ],
  "payment-status": [
    {
      "key": "paidTitle"
    },
    {
      "key": "paidText"
    },
    {
      "key": "pendingTitle"
    },
    {
      "key": "pendingText"
    },
    {
      "key": "failedTitle"
    },
    {
      "key": "failedText"
    },
    {
      "key": "retryLabel"
    },
    {
      "key": "referenceLabel"
    }
  ],
  "collection-media": [
    {
      "key": "alt"
    }
  ],
  "divider": [
    {
      "key": "label"
    }
  ],
  "heading": [
    {
      "key": "text"
    },
    {
      "key": "textHtml",
      "html": true
    }
  ],
  "form-text": [
    {
      "key": "label"
    },
    {
      "key": "placeholder"
    },
    {
      "key": "description"
    }
  ],
  "form-number": [
    {
      "key": "label"
    },
    {
      "key": "placeholder"
    },
    {
      "key": "description"
    }
  ],
  "form-select": [
    {
      "key": "label"
    },
    {
      "key": "options",
      "list": "labels"
    },
    {
      "key": "placeholder"
    },
    {
      "key": "description"
    }
  ],
  "form-address": [
    {
      "key": "label"
    },
    {
      "key": "description"
    },
    {
      "key": "provinceLabel"
    },
    {
      "key": "wardLabel"
    },
    {
      "key": "detailLabel"
    },
    {
      "key": "provincePlaceholder"
    },
    {
      "key": "wardPlaceholder"
    },
    {
      "key": "detailPlaceholder"
    },
    {
      "key": "placeholder"
    }
  ],
  "form-discount-code": [
    {
      "key": "label"
    },
    {
      "key": "placeholder"
    },
    {
      "key": "description"
    },
    {
      "key": "buttonLabel"
    },
    {
      "key": "appliedText"
    },
    {
      "key": "unknownCodeText"
    },
    {
      "key": "codeNotUsableText"
    },
    {
      "key": "quoteFailedText"
    }
  ],
  "form-radio": [
    {
      "key": "label"
    },
    {
      "key": "options",
      "list": "labels"
    },
    {
      "key": "description"
    }
  ],
  "form-payment": [
    {
      "key": "label"
    },
    {
      "key": "description"
    },
    {
      "key": "methods",
      "list": {
        "itemIdKey": "value",
        "textKey": [
          "label",
          "description"
        ]
      }
    }
  ],
  "form-timeslot": [
    {
      "key": "label"
    },
    {
      "key": "description"
    }
  ],
  "form-checkbox": [
    {
      "key": "label"
    },
    {
      "key": "options",
      "list": "labels"
    },
    {
      "key": "description"
    }
  ],
  "form-date": [
    {
      "key": "label"
    },
    {
      "key": "description"
    },
    {
      "key": "dayPlaceholder"
    },
    {
      "key": "monthPlaceholder"
    },
    {
      "key": "yearPlaceholder"
    },
    {
      "key": "dayLabel"
    },
    {
      "key": "monthLabel"
    },
    {
      "key": "yearLabel"
    },
    {
      "key": "timeLabel"
    }
  ],
  "form-calendar": [
    {
      "key": "label"
    },
    {
      "key": "description"
    }
  ],
  "form-file": [
    {
      "key": "label"
    },
    {
      "key": "placeholder"
    },
    {
      "key": "hintText"
    },
    {
      "key": "description"
    },
    {
      "key": "buttonLabel"
    }
  ],
  "form-paragraph": [
    {
      "key": "text"
    }
  ],
  "form-link": [
    {
      "key": "text"
    },
    {
      "key": "linkText"
    }
  ],
  "form-step-button": [
    {
      "key": "text"
    }
  ],
  "form-submit": [
    {
      "key": "text"
    },
    {
      "key": "submittingText"
    }
  ],
  "form-title": [
    {
      "key": "text"
    }
  ],
  "image": [
    {
      "key": "alt"
    }
  ],
  "image-comparison": [
    {
      "key": "beforeAlt"
    },
    {
      "key": "afterAlt"
    }
  ],
  "list-dataset": [
    {
      "key": "loadMoreLabel"
    }
  ],
  "list-item": [
    {
      "key": "text"
    }
  ],
  "product-image-feature": [
    {
      "key": "alt"
    }
  ],
  "search-input": [
    {
      "key": "searchPlaceholder"
    },
    {
      "key": "searchClearLabel"
    },
    {
      "key": "searchToggleLabel"
    }
  ],
  "tab-content": [
    {
      "key": "label"
    }
  ],
  "text": [
    {
      "key": "text"
    },
    {
      "key": "textHtml",
      "html": true
    }
  ],
  "text-marquee": [
    {
      "key": "text"
    }
  ],
  "text-marquee-item": [
    {
      "key": "text"
    }
  ],
  "breadcrumb": [
    {
      "key": "crumbs",
      "list": {
        "itemIdKey": "id",
        "textKey": "label"
      }
    },
    {
      "key": "homeLabel"
    }
  ],
  "menu": [
    {
      "key": "menuItems",
      "list": {
        "itemIdKey": "id",
        "textKey": "label"
      }
    }
  ],
  "chat-widget": [
    {
      "key": "title"
    },
    {
      "key": "launcherText"
    }
  ],
  "qr-code": [
    {
      "key": "alt"
    },
    {
      "key": "value",
      "when": {
        "key": "source",
        "equals": "text"
      }
    }
  ],
  "bundle-items": [
    {
      "key": "heading"
    },
    {
      "key": "quantitySeparator"
    }
  ],
  "search-keywords": [
    {
      "key": "keywordItems",
      "list": "strings"
    }
  ],
  "locale-switcher": [
    {
      "key": "panelTitle"
    }
  ],
  "theme-switcher": [
    {
      "key": "lightLabel"
    },
    {
      "key": "darkLabel"
    }
  ],
  "sale-badge": [
    {
      "key": "text"
    }
  ]
};

/** Content an element keeps in `config` (base only), addressed as `CONFIG_FIELD_PREFIX + key`. */
export const TRANSLATABLE_CONFIG: Record<string, TranslatableFieldSpec[]> = {
  "text-dataset": [
    {
      "key": "textValue"
    },
    {
      "key": "moreText"
    },
    {
      "key": "lessText"
    }
  ]
};

export const CONFIG_FIELD_PREFIX = "config.";

/** The columns a translation may rewrite on each entity, SEO fields included. */
export const TRANSLATABLE_ENTITY_FIELDS: Record<
  string,
  Array<{ key: string; html?: boolean; multiline?: boolean; list?: string }>
> = {
  "product": [
    {
      "key": "title"
    },
    {
      "key": "description",
      "html": true
    },
    {
      "key": "vendor"
    },
    {
      "key": "attributes",
      "list": "attributes"
    },
    {
      "key": "slug"
    },
    {
      "key": "seoTitle"
    },
    {
      "key": "seoDescription"
    },
    {
      "key": "seoKeywords"
    },
    {
      "key": "ogTitle"
    },
    {
      "key": "ogDesc"
    }
  ],
  "category": [
    {
      "key": "title"
    },
    {
      "key": "description",
      "html": true
    },
    {
      "key": "slug"
    },
    {
      "key": "seoTitle"
    },
    {
      "key": "seoDescription"
    },
    {
      "key": "seoKeywords"
    },
    {
      "key": "ogTitle"
    },
    {
      "key": "ogDesc"
    }
  ],
  "article": [
    {
      "key": "title"
    },
    {
      "key": "summary"
    },
    {
      "key": "content",
      "html": true,
      "multiline": true
    },
    {
      "key": "tags"
    },
    {
      "key": "slug"
    },
    {
      "key": "seoTitle"
    },
    {
      "key": "seoDescription"
    },
    {
      "key": "seoKeywords"
    },
    {
      "key": "ogTitle"
    },
    {
      "key": "ogDesc"
    }
  ],
  "blogCategory": [
    {
      "key": "title"
    },
    {
      "key": "description"
    },
    {
      "key": "slug"
    },
    {
      "key": "seoTitle"
    },
    {
      "key": "seoDescription"
    },
    {
      "key": "seoKeywords"
    },
    {
      "key": "ogTitle"
    },
    {
      "key": "ogDesc"
    }
  ],
  "course": [
    {
      "key": "title"
    },
    {
      "key": "summary"
    },
    {
      "key": "description",
      "html": true,
      "multiline": true
    },
    {
      "key": "level"
    },
    {
      "key": "instructorTitle"
    },
    {
      "key": "instructorBio",
      "html": true,
      "multiline": true
    },
    {
      "key": "tags"
    },
    {
      "key": "slug"
    },
    {
      "key": "seoTitle"
    },
    {
      "key": "seoDescription"
    },
    {
      "key": "seoKeywords"
    },
    {
      "key": "ogTitle"
    },
    {
      "key": "ogDesc"
    }
  ],
  "courseSection": [
    {
      "key": "title"
    }
  ],
  "courseLesson": [
    {
      "key": "title"
    }
  ],
  "page": [
    {
      "key": "title"
    },
    {
      "key": "description"
    },
    {
      "key": "keywords"
    },
    {
      "key": "ogTitle"
    },
    {
      "key": "ogDesc"
    },
    {
      "key": "slug"
    }
  ],
  "uiString": [
    {
      "key": "text"
    }
  ],
  "mailString": [
    {
      "key": "text"
    }
  ],
  "siteLabel": [
    {
      "key": "text"
    }
  ]
};
